#include <stdio.h>
int main(void) {
    // 아스키 아트를 넣을 때, 먼저 visual studio 창에 복사/붙여넣기를 한 뒤,
    // Alt + 드래그를 이용하여 아스키 아트 내용을 복사하였고 내용의 줄 수 만큼
    // printf("\n");를 써넣은 뒤에 맨 윗 줄의 printf("\n"); 안에 붙여넣기 하였다.
    // '\'를 출력하기 위해서는 printf 안에 '\'가 아닌 '\\'를 사용해야 합니다. 
    // 해당 아스키 아트에는 '\'가 없었기에 따로 처리는 하지 않았습니다. 
    // 프로그램을 시작하여 콘솔에서 아스키 아트를 보기 위해서는 폰트 크기를 최소인 5로 설정한 뒤에 콘솔창을 꽉차게 해야 합니다.

    printf("/+yossossooossssoosssssyssossosssssssssssssssssssssssssssssssysyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhyyhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhyyyyssssssssoo++++++oooo//+ohhhoooo++++++oossyssssoooooooosssyssoo++++++++++++++++++++++++oossyyyyyhhhdddddmmdhhyyyssooo+++++++++++++++++++++oossyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssyhhhysssooooooooooossyyhhhhhhhhhh\n");
    printf("sosossssssososssssssoossyyssosoooooooooooooooooosssssssssssssysssssssyyyyyysyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhdhhhhyyyyyysyyyysssooooo+++++//+oddd+++++oosyyyyyyysssssssssssssoo++++++++++++++++++++++++oosssysyyyysssyyyyyyyyyyysso+++++++++++++++++++++ooossyyyyyyyyyyyyyyyyyyyyyyyyyyysssooo++++oddyooooooossyyhhhhddddhhhhhyyyys\n");
    printf("o++oooo+ooossoosssssossssosyysoooooooooooo++++++++++++oooooossssssssyyyyyyysssyssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhyyyyyyyyyyyyyyyyyyyyyyysso//+++/++ossyyyyyhyyyyysyssysssoo+++++++++++++++++++++++oossyyyyyyssssssyyyyyyyyyssoo++++++++++++++++++++oossyyyyyyyyyyyyyyyyyyyyyyyyyyysssooooooooo+++++odmyosyyhhhhhdhhhhhhhhyyyyssssssy\n");
    printf("ooooosy++:/o+ooo+++oosss++++os+++ossssooooo++++++++++++++++++++oooosssssssssssyysssssssssssssssssssssssssyyyyyyyyyyyyysssssssyyyyyyyyyyyyyyyyyyyyyyyyyhyyyyyyyyyyyyyso+/--:/syyyhhyyyyyyyyyyyssoo+++++++++++++++++++++ooossyyyyyyyyysssyyyyyyyyysoo+++++++++++++++++++oosssyyyyyyyyyyysyyyyyyyyyyyyyyssooo++++++++++o++o++/+++++syyhhhhhhhhyyyyyyyyyyyyyyyysso\n");
    printf("sooo+sy+/:+o+++++++++oooo++++y++oyhssssooo+++++++++++++++++++++oooooooosooooosssssssssssssssssssssssssssssssssssssssssssyssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyso:.``-syyhhhhyyyyyyyyyssoooo+++++++++++++++oossyyyyyyyyyyyyyssyyyysssoo++++++++++++++++++oossyyyyyyyyysssssyyyyssyyyyyysssooo+++++++++++++oosssyyyso+::::/ossyyyyysssyyyyyyyysssoooooooo\n");
    printf("sysssys+/:/o+++++++++++oo++++oyhhhhsssoooo+++++++++++++++++++++oooooooooooooooooooooooooo+++++++oooooosssssssssssssssssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyysso+++osyhhyyyyyyyyyyyyyyhyyyyyyysssssssssyhhhhyyyyyyyyyyyyyysssoo+++++++++++++++++oossyyyyyyyyyyyssysssssyyyyyyysssooo++++++++++++ooossyyhhhyyyyyyso:````:oosssyyyyyssssooooooooooooooss\n");
    printf("+o+++++///+osossssso++++so+osyhyhhysssoooo++++++++++++++++++++++++++oossssoooooooooooooo++++++++++++++++++++oooosssssssssssssssssssssssssssssssssyysyyyyyyyyyyyyyyyyyyssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhdhhhhhhhhhhhyyyyyyssoooo+++++++++++++++oosyyyyhhhyyyyyyyyyssssyyyyyyssssyysssoooo++++oossyyhhhhhhhyyyyyyyssssoo+++++osssssoooooooooooosssssssssssss\n");
    printf("+oo++//+++//+++oosssyhysoosyyyhhhhssssooo++++++++++++++++++++++++oosssssssssoooooo+o+++++++++/////++++/+++++++++oooooooossssssssssssssssssssssssssooooossssssyyyyyyyyyyyyyyyyyyyyyyyyhyyyyyyyyyyyyyyyyyyyhhddhhhhhhhyyyyyyhhhyyysssssooooooossyyhhddhhhyyyyyyyyyyyyyyyyssssoooo++++hdyooosssyyyhhdddhhhhyyysssssssssyyssssoooooooooooooossssssyyssssssssssssss\n");
    printf("+oo+++++++++++ooooooooooodmNNmmmmdhysoooooo+++++++++++++++++++oossssssssssssoooo++++++oo++++++++++++++++++++++++oooooooooooosssssssssssssssssssoosoo+++ooooooosssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhddhhhhhhhyyyyyyyhhhhhhhhhhhhhhdddddddhhhhhyyyyyyyyyyyssoooooo++oo++//++yhyyyhhhhhhhhhhhyyyssssssyyyyyysssoooooooooooosssssssyysyssyyssssssssssssyy\n");
    printf("oooooooooooooooooooooo+/odNMMMMMNNNNNdyoooooooooo+++++++++oosssssssssssssooo++++++oooo++++++++++++oosssssssssooooooooooooooosssssssssssssssssssssssooooooooooosooooooosssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyhhhyyyyyyyyhhhyyhhhhhhhhhhddddddddddhhhhhhyhhhhyyssoooooooooosssyys/+++++syyyyyyyyyyyyyyyyyyyssssssooooooosssssssssssssssssssssssssssyyyyyyyyyyyyy\n");
    printf("sssssooosyyso++o+osooss/+hmMMMMNNNmmmmdysssssooooooooooossyyysssssoooooooooo++++osyysooooooo++oosyysssssssoooooooooooooooosssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhddddddddhhhhhhhhhhhhhhhhhhhhhhhhddddddhys/...-osssyyyyyyyyyssssssooossssssyyyyyyyysssssssssssssssyyyyyyyyyyyyssssssssss\n");
    printf("+ooooooossssooossyhsyddyshmMMMNNNmmmmhyyyhyyyyyyyyyyyyyyyyyyssssssssssooooooooo/+osdmsoooooossyyyssssso++++oooooooooosssssssssssssssooossoooooooosssssssssssssssssssssssssssssssssssssssssssssssssysssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhddddddddhhhhhhhhhhhhdhhhhhdddddddddhhyso+/:/+syyyyysssssssssssyyyyyyyyyyyyyyyyhysssssssyyyyyyyyyyyyyyyssssssssssssssss\n");
    printf("oosssss+////+++++oosssshdmNNNNNNNNmdmhyyyyyyyyyyyyyyyhhhhhyyyysyyhyyyyysssssooo:.:/+soossyhyyyyyssoo+++oooooooosssyyyyyyyssssssssooooooooooooooooooooossssssssssssssssssssssssssssssssssssssssssssssssssssssssyssssssssyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhdhhhhhhhhhhddddddddhhhhhhhyyyyyhhddddhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyysssssssssssyssssssssssssssssss\n");
    printf("/+soooo+/:+/++++++++++oooymNNNNNmmmmmhyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhyyyyys/.`.+syyhhhhyyssoooooosssssssyyyyyyyyyyysssssssssooooooooooooooooossssssssssssyyhhdhhhhyyyyyyssssssssssssssssssssssssoosssssssssssssssssssyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhdhhhdddddddddddddhhhhddddddddddddddhhhhhhhhhyyhhhhhhhyyyyyyssssssssssssssssssssssssssssssssssss\n");
    printf("::/+++os/:+/+++++++++++ooymmmmmmmmmmmhyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhyyyyyyso++oyyhhhhyyyyyhhhhhyyyyyhdhhhhyyyyysssssssssosoooooooooooooossssssssssyyyhhdddddddddhhhyyhhhhhhhhyyyysssssssssssooosssssssssssssssssssssyyyyyyysysssssssyyyyyyyyyhhhhhhhhhhhhhhhhhddddddddddddddddddddddddddddddddhhddddddhhhhhyyyyyyyysssssssssssssssssssssssssssssssssssssy\n");
    printf("oo+ossys+/+/+ooo+++++++ooydmmmmmmmmmmhyyyyyyyyyyyyyyyyhhyyyyyyyhhhhhhhhhhhhhyyyyyyyyhhdddddhddddddddddddddddhhyyyysssssssoooooooooooooossssssssssssssyyhhhhhhhhhhhhhhhhsssyhdddhhhhhhhhhhhhhhhyyyyyyyyyyyyysyyyyyyyyyyyyyysyyyyyyyyysyysyyyyyyyyyyyyyyyyyyyhhhhhhhhddddddddddddddddddddmddmmmmmmmmddddddhhhhhhyyyyyssssssssssssssssssssssssssssssyyyyhhhhhdddd\n");
    printf("+++++++++///++oooooosssooo+o+++oosyhhdhyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhyyyyyhhhdddddddddddddddddddddhhyyyssssssssoooooooosssssssssssyyyyyyysyyyyysssyssssssssssssyddhyyssssssssssssssysysyyyyysssssysyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhdhhddddddddddddmmdmmmmmmdddddhhhhhhyyyssssssssssssssssssssssssyyyyhhhhdddddmdmmmmmmddd\n");
    printf("+o+ooo++++++++oso+/++++oo/---....--::oossssssssssssyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhddddddddddddddhhhyyyysssssssssssssssssyyyyyyyyyyyyyyyysssssysssssssssssssssssssyyyyssssssssssssssssssssyssssssssssssssyyyysyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddmmmmdddddhhhhyyyyyyyssssssssssssyyssyhhdddddmmmmmmmmmmmmddddhhhyyy\n");
    printf("oooooooo++++++ooo++++++++--..`   ....+ssssoooooo+++++++++++++osyyyyyyhhhyyhhhhyyyyhhhhhhhhhhhhdddddddddhhhyyyyssssssssssssyyyyyyyyyyyyssssysssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssyssyysyyyyyyyyyyyyhhhhhhhhhhhhddddddddddddddddddmmmdddddddddddddddddddddddddddddddddhhhhyyyyyyssyyyyhhhhddddddsyddddddmmmmmmmmdmNdmNddhhhhddhd\n");
    printf("oooooooo+o+++o+++++++++++..       `../yyyyyyyyyyyssssssooo+++oosyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhddhhhyyssssooossssyyyyhhhhhhyyyyyyyyyyyyyyyyyyyyyyssssssssysssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssyyyyyyyyhhhhhhhhhdhddddddddddmNNmdddmmmdmmmmmmmmmmmddddddddddhdddhddhyyyyyhhhddddmmmmmmmmmmmmddddhohddddddmmmmmmddddhydmhmdmddddhd\n");
    printf("++++++ooooooooooooo++++++``         `:sssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssoooosssyyyyhhhhssooo++oosssyhhhddmdmmddddddddddhhhhhyyyyyyyyyyyyyhddddddddddhhdhhhhhhhhhhhhdddhhhhdhhyyyyyyyyysyyyyyyyyyyysssyyyyyyhhhyyyyhhhhhhhhhhhhddddddddddmmmmmdhdmmmmmmmmmmmmmmmdhddhhhysossosyyoshdddmmNNNNNNNNNNNNmmmddhhhhyohddddddmmmmddhhhhhhdmmNmmddddmN\n");
    printf("++++++s+::///////++ooooo+`.         `-ssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssooooooooosooooossssyhddddddddddmddddddddddhhhhyyyyyyyyyyyyyyhNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdhydhddhdddhhhhs+::yydmmmNNmddddmmmmmmmmmmmmmmmmmmmmmmmmmNmmyymNNNNNNNNNNNNdhysyyosyssyysoyysoyddmmmNNNNNNNNMMNNNmmmmdddhhsshdddddmmmmmmmdhhhhmNNNNNmmmdddh\n");
    printf("+++++oyo:::++/+/////+++++.-.`     ```:hyhhhhhhddddddddddddddddddhddhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyhhddddddddddmddddddddddddddhhhhhhyyyyyyyyyyyhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdhysydmmddddhyso+:-:+sddmmNNNmmmmmmmmmNNmmmmmNNmmmNNNNNNNNNNNNNdmNNMMMMMMMMMMMdhhhhysysssyyyyyyyoydmNMMMMMMMMMMMMMMMNNNNmmdddssdddddmmmmmmmmmdhhyhyyyssssssssy\n");
    printf("oo++++yo:::+++/++//+++++///::--......:hhhhdhhddddddmdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddhhhhhhhyyhmmmmmmmmmmmmmmmdddmmmmmmmmmmmmmmmmmdysshdmmmddhhyo/-.:/oyhdmmmmmmmmmmmNNNmmmmmmmmmmmmNNNNNNNNNNNNNNNdmNMMMMMMMMMMMNddysysyhysssyssssyohdmNMMMMMMMMMMMMMMMMMMNmmddhsyhhhhyyyyyyssssssyyyyyyhhhhhhhhh\n");
    printf("ooooooso/::++++++/++++++/yddhhhyyyssoohhhhhyyhhdddddddddddmmdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddmmNNNNNNmmmdhhhhdhyyhdhyyhdddmmmmmmmmhhmmmddddhyo+:..:+yhddmmmdmmmmmmmmmmmmmmNmmNmmmmmmmmmmmmmmmmmmmmmdmmNNNNNNNNNNNmhhyyysyddddddyyyyyyddmmMMMMMMMMMMMNNNmmddhyyyssossssyyyhhhhhhhhhhhhhhhhhhhhhyyyy\n");
    printf("/+////+//::/++ssoosssssoshmdddddddddddddddhhhhhhhhhhhddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdhhdmNNMMMMNNNNmdmmhhhhhyyyyyssssydmhsshmmmmmmdhhs+-.-++oyyddmmmmmddmmmmmmmmmmmmmNNMMNN+:::::::::::::::::::::::::::::::://///:+NNNNNhyyyyyyymmNNNNNmmddhhhhyyyyyyyhhhddhoyhhhhhdddhdddddddhhhyyysssssssss\n");
    printf("sssosoyyso+/+/+++ooooooydmmmmmmmmmmmmmddmmmdddddhysssssssssoooymmmmmmmmmmmmmmmmmmmmmmddddhssssssyyyyyhhhddddddmmmmmmmmmmmmmmmmmmmmmmmmmmNNmmmmmmmdmdhsyhdmNNMMMMNNNMNmmNmhhhhhhyyyyyssoosydmmmmmdddds/..:+syyyhyhddddddddmmmmmmmmmmmmmNMMMMm:--------------------------------------+MMMMNdyyhddyhdddddhhhdddddmmmmmmmmmmmdddhohhhhhhdddddddddhhhyyyyyyyyyyssss\n");
    printf("sssoosssso++++++osooooosydmmmmmmmmmmmmmdmhssssyy+://++++oo+/++smmmmmdmmmmmmmmmmmmmmmmyhdmhyyyssssooooossssssssymmmmmmmmmmmmmmmmmmmmmmmmmNNmmmmmmmmmhhmMMNMMMMMMNMNmmNmhmNdhyhhyhhysssssyyhdmmddhyhdd+o+syhhhhyo+syyhddddmmmmmmmmmmmmmNNMMMMm---------------------------------------oMMMMNdhyddhyhddddmmmmmmmmmmmmmmmmddhhhyysohhhhhhhdddddddhhhhhyyyhmdmmmhyyy\n");
    printf("sssssssss++++++ossooo++oydmmmmmmmmmmmmmdmy/+++os: ````````    .ddmmmmmmmmmmmmmmmmmmmd:.-y-````........::///--:ommmmmmmmmmmmmmmmmmmmmmmmmmmmdmmmmmmddNMMmNMMMMMNmNMMmhmyyydhyyyyyyhhysshhhhhhhho:-+hddddddddhs/.`-oyhddhhdmmmmmmmmmmmmNNMMMMd---...---------.-.--------------------.sMMMMNddddddshddddmmmmmmmmmmmmhhdhyhhhhhhsohhhhhhhhdhddhdhhhhhdyyydhmddhhdd\n");
    printf("oooosssssoosoooosyso+++ohdddhhhhhhhhhhddmy++++os/  ` ``````   .dddmmdmmmmmmmmmmmmmddd-`.s-    ``      .`.`.   -ddmmmmmmmmmmmmmmmmmmmmmmmddhdmmmmNNNMMMMMMMMMMNNdmMMMmhhhsyhyyhhhhyhdysoydhyys:.-/sdmmmmddhdy+-``-osyyyoydmmmmmmmmmmmmmNMMMMh.-.----------.........----------------.hMMMMNhhhddhydddddmmmmmmmmmmmmyhdhydhhhddoshhhdddyddhddhddhyhhdyyyyhdhhddNm\n");
    printf(":::://+/:/://///+oossyyhdmmmmmmmmdmhsyhdmyssoooo/  . `.``.`   .dddddmmmmmmmmmmmmmmddd-``s-     `.`    ..-.-  `:ddmmmmmmmmmmmmmmmmmmmddddmdhdmmdNNNNMNMMMMMMMMNMmymNNmhdhdhssyyhhyysyhhysossyyhsshdmmmmmdhyds+oo++oos++s+ymmmmmmmmmmmmNNMMMMy......---.---.....---..--.----.-------.dMMMMmhhhhhyydddddmmmmmmmmmmmmyhhhhdyhdmdoyhhddddhhhhhyyhhdmNmmdhhhhhmmmNNm\n");
    printf("::::::so::.:+++++++++++oodmmmmmmdmmhosyhms++++++/``.``.``.    .hddddmmmmmmmmmmmmmmddd:``s-      ```   ..``.`  :mdmmmmmmmmmmmmmmmmmdhhdddhyhdmmmmmmNNNNMMMMMMMMMNdyhhmdddmmmdyyhssysosdmhyyhssymmdhdmddhhyydhyssosyyysyhhmmddmmmmmmNNNNNMMMMs........................-.-.--...------mMMMMmdddhhyydddddmmmmmmmmmmmmyssddhssdmd+hhddddmmmdmhhdmmNNmdddhhyyyyyysso\n");
    printf(":::::-/s::.:+/+++++++++oohmmmmmmddms`..:s/--```````````` .    .dddddmmmmmmmmdmmmmmddd-`.s-   `   ```  .```.`  /ddmmmmmmmmmmmmmmmmddddddyoshmmhhhhdmmmNMMMMMMMMNNdssyyshdmNmmdyymssyyssmmhdNmyosmmdhhhhhyyymmhsssoooosyydmmddmmmmmNNNNNNMMMMo....................--..-........----.-NMMMMmmhdddyhdddmmdyydNNNNmmNdysommddsydhohhhhhyyyyyyysssoooooossssoooooooo\n");
    printf("oo+/+/os::-+s+:o/+++++o++hmmmmmmddmo -`-o-.-`````````.```.``` .dddddmmmmmmmddmmmmmddd-`.y- ````   ````.```.`  /ddmmmdmmmmmmmmmddhhhhhhhoosdhysssyyhhdNMMNmNMMNmyo///++oydmmmdhhymhhdhhdNdhmMNhsydmdhyyhyyyhhhddhyssydddmmmmmmmmmNNNNNNMMMMN+.-.....--.--...........-..-..--------.:NMMMmddhdddyhddmmNNNmNNNmddddysosyysooooooooooooooooosssssssssyhdhyssssssyy\n");
    printf("///////::::://:/+sssyyyssdmmmmmdddds`-.-o-`.````````.``````   .dddmddmmddmmddmmmmmddd-`.y- ``     ````..``-.  /ddmmmmmmmmmmmmddyyhyhhhs++shyooyoosyyymNNmdmNNho/::::::/ohhdddddhhdmdhhhmNdmMNNdyhmmddysyyssssyyyhhyhhhdddmmmmmmNNNNNNNNNNNN/....-...----......................---.+MMMMhmdhddhsdddhhhyyssssooossyhhsoooooooooooossssssyyyyyyhhhhhhdddddddddddd\n");
    printf("/+++///+o++++++++////++shhdddmddddds`-.-o-``.` ``.`..`.````` `.dddddddmdddmddmmmmmddd-`.y-           .````.:``+mmmmmdmmmmmmddhyyyyyhdy+/+ssoos+++ooyyhhmmdmmho/:------::ydhhdyhhydhmhydymmmNNNNdydmdddhyysssysyyhhyhhhdddmmmNNNNNNNNNNNNNNN:.........-.-..........................oMMMMhmdhhhhsossssoooooosssssyydyyyhhhhhhhyyhhhdhhyyhddddddddddddmmmmmmmmmmm\n");
    printf("/++++ooosoo+ooooo+oo+oosyyysssyyhhhs`---o:`````...`....` .`.`.-ddddddmmddmdddmmmmmddd-`-y-```` ```    .``.`-``+ddmmddmmmmmdhsssyyyydhy+/+oo+oo++/o+oyyhdNhdho/----------sdhhydyyyhhmdyhyyNdmdmmNhhdddmmmhsssyyyyhhhhhdddmmNNNMNNNNNMMMNNNmm-........-..-.........--....-...------.sNNNNhmddddhoooos+++++++ossshhhhhdddddmmddyyhhhhysssyhhhhhhhhhyyyhhddddddddd\n");
    printf("//++++++oo+++oooooooooososddyhysyhhs`..-o-````..```-``.` . ....dddddddddddddmmmmmdddd-`-y:` ```.```   `````.  +ddmmmdmmmmmhooooyyyhhys/:+ooooo+//o++oyshmhyo/:---------:sdhhyhhshydmdyhyymdhyhhNdhhdNNmmNdyyyyyyyyhhdmmNNNMNNNNNMMMMMMNNNmm-..........--..---------...-.....-----.hmmmdymddddyssooo++++++oosssssyysyddddddhysyyhyyso+osyyhhhhhhyssyosyhyyyhhhy\n");
    printf("ooooso+oooos+ooooooooo+soshddhhyyhys`.--o-``.......-..-``..`  .dddddddddddddddddmdddh-.-y/-+os++///+/+++++oo++yddmmmmmmmmds+ooyyyhhhyo///+o+o++//o++osoydho/:----...-.-/hdyyyddyyydmhyyyhhdysyydmyydNNNmmmdhyyhhhhdmNNNMNNmNMMMMMMMMMMNNNNd-......................................sshdmymyhdhsssssoo++oooooosoososoyhhhhhysssyyyyso+//osyyhhhyysooso+syysyyyys\n");
    printf("+//::::/:///////+++oooossyhddhhhhhhs`.--o-`..` `.`````...`    `hdddddddddddddddddddhd+oydmmmsss//::::::::///::ydddmmmmmmdhooosyysyhyys++/++o++o/ooo+osssyy+:----------:sdhhssdhsyhdhhhsshymyosyhdhsymMNmmNmdhhddmNNNNNmmNNMMMMMMMMMMMMNNNNNhyyyyyyyyyyyyysooooooooooooooooooooooosdddddhdhhdds+o+++++++o+oo+oo+/.:+syyyyyysoosysss+///+syyyyyso++//++ossssyyso\n");
    printf("+/:://+y:--//////++++++//sddddhhhhhy`.-.o:```` ..`.   .-.` `  `hhdddddddddddddddddddddddNNNNmmhhhhddhhhhymmmmmmdddmmmmmdho+ossysoyyssy++o+oo+s++osoooyysss+:--....---:shhyhoyhyhhddyyyyshyyhosddmyssmNMNmNNmmmNNNNNmmNMMMMMMMMMMMMMMMMNNNNNNmNNmmmmNmmmNNdyyyyyyyyyyyyyyyyyhhhyyhhyyhyyhhsyhy++++++++++++oo+o+/` .+ssyyyyysoossssso///osyyyyso/:```:+ossosyyso\n");
    printf("::::/++y/--///+++++++++++oddhhhhhhhy`...o:```.```-`  ...` `````hhddddddhdddmmmdddmmddsydNNNhsooosssmyysssdsdddmmddmmmmmho/osooooossosy++soooso+oossosyyyssso/--...-:+yhhyyssyydhdddyhhhsyyshyymmNhyymNNNNNNNNNNNmmNNMMMMMMMMMMMMMMMMMMNNNNNmhmNNNmNNNNNNMdyyyyyyyyyyyyyyyyyhyyyhdsyhhhyyyoyyo++o++/+/+++oso+soo//+oyysysyysoosssso+++ossyyyso++:..-+ossyyyyyys\n");
    printf("//:oooos:--:/+++++++++++oyhhhhhhhhhy://+dhyyyysooso++ooo////::/hhddhddhhhhhddmmddddddsydNNN+ ..-ooodyyhho+`...hddddmmmhy/++o++o+oss+ooo+ssssoo+oosssyhyho+++/:---:oyyyyyhssysyyhmdyhhyyssyodyhmNNhshNMNNNNNNNmmNNMMMMMMMMMMMMMMMMMMMMNNNNNNdhmNNNNNNNNNNMhyyyyyyyyyyyyyssssyhyosssyhhoooossyssss+ssosssoyhohso+o+o+yyssssssssssoo+/++ossssssoo++++oossyyyyyyso\n");
    printf("oo+o+/::---:+ooooosssssssydhhhhhhhhhssshNNNNmmmmmmmmmmmmmmmmdddhhhddhyyyhdmmdddddmmdd/+yNNN+`..-/+odysooo/ -``hddddmmdho/+++/o+ooso++o+ooyyooo+oosssosossoooo++/+syyyyyyssssyyyhhyyssyysyssNhdNNNysyNMNNNNNNmmNMMMMMMMMMMMMMMMMMMMMMMNNNNNNhyNNNNNNNNNNNNhyyyyyyyyyysssssssyyyossoysssssooyyyooooooo+oo+hhsysyysssyhssssssssssoo+//+ossssyysssssoossssyyysssso\n");
    printf("///////////:+/++/++ooooosshhhhhhhhhhooyhNNNmyhyhddhhddddhhhhdddhyyyyyddddddddmmdddddd/+yNNN/ ``  `-dy/`.so-:/-hddddmdhh//+/++o+ooos++o+osyyo+::::/+/://+oo++/++oo++oo+///osyyyyhhyyssyhsyshmdmNMNyydNMNNNNNNmmmNMMMMMMMMMMMMMMMMMMMNNNNNNNNyyNNNNNNNNNNNmyssssssssssssssssssyysss+syssyyoossssssooo++o++hdssso+oyshhsssyyysssso++/++osssyyyyssssssssysysysssso\n");
    printf("+/+/+++++oo+y+++++/++++/-/yyyyhhhhhh//oymNNd--.+oooo+sso/-`...:syhddhdhhdddddddhhdhhhoshNNNy//--:/odss/:s+-.-.:///++++///o/++++oooy++ooosy+:`````.--..--::::::::///::-..-/+osyyhhhhhddyhhdmmNmNMNddNMMMNNNNNNmmNNMMNMMNNNNNMNNNNMNNNNNNNNNdsymmmNmmmmmmmhossssssssssssssssyhyoossooso+yssssssss+o+++ooo+hhhhhsyhhhhhyhhhhhysoso+//+oosssyyyyyyyysssyyyssssssso\n");
    printf("o+++++++ooo+o+oooo+oo++++yyyyyyyyyyh:/+ymNNm-:/+++oo+oo+/::/++ohhhhhdddddddddddhhdhhdhhdNNNNNmssyhhdhssydo-..-.--.-----/+o+ooossosyo+oso+-`````````````..--:::::----..`..-//osyyyyyyyyhdmmmmNNNMNNNNNMMNNNMMNNmdNmdMNdNNdmNdNNNNNNNNNNNNNmhohmmmmmmmmmmmyoossssssssssssssyhyyyyyo+ssssss+osooosssoo+oooooooyyhhhyydmmmddddyssso+//+oossyyyyssyyyssyyyysssssss+\n");
    printf("ooooooooosoooossssssooosoyhdhhhhyyyh//oymNNm--:+++oosssss+/-...hhhddmddhhhhddddhddhdmmmmmmmmmmdmmmmmmmmdmo.-:---:--:--:/+sosyoyssyys+/:-`` ``````.--:::///////::--..````.:/+osssoo+++oyyhhddddmmNNNNMMMMMMMMMNNmNNmNNmNNmmNmNMNMMMMNNmmNNmhohmmmmmmmmmmdyoosshddmhsssssyhhhyysyyoooo+ooo+ooossooooo+sosossoyyyyhyyhNNNmmmmmmmdddhhhhdddddddhhhhhysosyyhyyyysss\n");
    printf("://:::/::::://///+++osssyddddhhhyhhh+/oymNNm---///ssysoo/` `:+sdhyhhhyhhhdddmmdddddddddmmmmmmmdmmmmmmmmdmo.--.---.-----/+sysssossssy:```` ```.-:+oo/-/ohddhso+/::.``````-:+osso+//::-::/+osssyyyhmNMMMMMMMMMMNNmNNNNNmNNmNMNMMMNNNNNNmmNNmhohmmmmmmmmmmhysssssyyysssssyyyhyss+yyys+++ooooosssssossooooo+yssyyyyyyyymmmmmmNNmmmmmmmmmdmmddmmmmmmdy+/osoossso++o\n");
    printf("/////:y+---:+//:::::///++sdddhhhhhhh++oymNNm:-:+ssyys/-:.`.--+-hh+syyyyyyyyhhhhhhdddddddmddddddddhddhhyyh/------..-----:oy++ooosoyyo.`````````.....---+syys+so/:-``````.-:osss+/::://////++ooooosymNMMMMMMMMMNmhmdhNmymmydmhmMMmmmmmNNdmNmhodmmmmmmmmmmhsssossssssssyhyyyhsoooss+ossssso/+oossssooo++ossssshhhydhhhmhhdyhy++o+++::/:::::/+++oyhyo+++o//ooo++//\n");
    printf("////sso::--///://////++oosdddhhhhhhhssyhmNmdyyso++/+oso+/:/+osohy+yhdddddddddddhhhhhddddddddhhyyysoo/--/ysssssoo+/:/:++/+o/+/:+soss:`````````````...---://///:--.``````.-/osss+/syshdddmyyyysssssshmNMMMMMMMMNmymdhNdymmyddydMNmmmmmNmohNmhsmmmNNmmmmmmysssossyyyssyhhyyyhsso+so+ooo+oo+++oosssossooososyyyyysssssoo+os++/-:/+ososssssssysssyyyyso+oo/+sso+///\n");
    printf("o+oyy+/:---://////+sysssssdddhhhhhhhhyhhhhdddmoohyhddysyyydddmdyhdmmmmmNNmmmmmmmmmdddddddhyysooydyss++yhhhhhyyyyhhhhso+/+/::../o+oo-````````````.......-----...````````.-/osss+++///+ossosyddhysssyhNMMMMMMMMNmdmddmddmmdddhmNmmmmmmNdsdNmhsdmNNNNNNNNNmyssssyyysyhdhyyyyhyso+oo+oo+/+++++ossysossssssossys:--:`./`-.`:-.```.+osyhhhhhyyhsyhdmdhhyyhddhho+++oo\n");
    printf("++///:------//++ooosso+oshddddhhhhhhhhhdhhhhhhdddddhhhhhhhhhhyyhmmmmmmNmmmmmdddddddddhhhys++ohmmmdhyhhhhyyyyyyyyhhhdmdyo/--. `-/+//`````    `````...........```````````.-/ossoo+///+++++++oosyssssshNMMMMMMMNmdhhhhhhyhhhhhhhhhhhdddddhdmmh+/+mmmNmmmmmNo+ssyyyyyyhhyyyyyyysssso/so++o+//++oossyyy+syyyysso-..-..:.-..::..`.-+oyyhhhhhhyhhmNNmdhhddhmNmy++osyy\n");
    printf("....-...........-.------/oddddhhyshdhhhhhhhddhhddmmdhhhdhhhhsoydddmmmmmmdmmdhdddddhhhyyss++oydmdyyssyssyyssyyyyhhddhhdddh:.```-//:-`````      `````..........`````    `.-/ossso+///////++++++++oosshNMMMMNMNddhyyyyyyhhhhhhhhhhhhdddddddhhy//oNmmmmmmmmm++/osyyyyyyyyyyyyyss/o++++oo/ss++++yyysyyssyysssss+``.-..:.--.:/..`--+oyyhhhhhhhysdNNdhhhyyhhhhyooydmm\n");
    printf("...`--.----....--..---.-::dddhos:/sydddmdhhhhhhhhddhhhdhhhhs+osyyyhhhyhhhhhhyhhhhhhyyyssssooyhhdsosyhhsssyyyhhhyhddmmdmmm+``.---:-.``````      ````..........```````  `.-/ossso+//::::::::::::/+ooshMMMMNNNmhhhyyhhhhhhhhhhhhhhhddddddddddy++ymmmmdmmmmmoo+osyyyyyyyyyssssssoss+++o+/+o/o+oyyysyssosysssssy///+/+s+++/+o///++osssyyyysyy+odNNNmhs//ossyddhydNN\n");
    printf(".-...-.-.--...---::::----:myy:-:`-y:/dsddhhhhyhyshhhddhhhhy+++oooossssssyyyhyyyyyyyyyssssssosyyhyyhdmmdhyyyyyhhhyhmmNNmNm/`..`` `..````````     ```...........`````````.-/+ossoo+/:::------:::/++osdMMMNNmmdhyyyhhhyyyyyhhhhhhhhddddddddddhssyo+++++++ohssosyhhyhyyyysssssoooooooos++++/ooshhhhhhy+sysssyymMNNmmNNNddhyyyhhhhhdoososs+soymNMMMNy/-+oyhymhysdMM\n");
    printf("/o++++++/:/+::::://+++//oyd/+-//./ss+syddhysyyyhhhhdddhhhdo++oooooosoossyyyhyyyyysssssssssssossdddddmmmNNdyssydddhNNMNmNd.````` ```````````    ````..-----::..`````  ``.-/+ossso+/::------::::/++osdMMNmddhhyyyyyyssssyyyyyhhhhdddddmmmmdddhys++/////++++ooooddyhhhhyssssyysoyyss/+s+oooooshhhsysooooosssohMMMNNNMNmdhshssyyhhhossssyyssdmMMMMms.`//hmyhs+omMM\n");
    printf(":::::///:::::::/+/++++++shh/yo+o++syyhdddhysyhddddddhhhhhsoooooo+ooooossysyyyssssssssssssysoosshyhdddmNMMMmhdhmNNdNNNNNNh`````-```````````````````..--::///:-.`````` `..-/+osssso/::-----:::://+ossdNNhyhdhyyyyssoooosssyyyhhhhdddmmmmmmmmddhyoo+////:/::::/hmhyhyhyyyyysyssossoo://+/++ssyhhhyyyssyyyyyyssNMMNNNNmdysohyssyyhyysyssyssyNMMMMMd+`.:+dNhs+-+NMM\n");
    printf("/////+oo/--.::/osoosoooossdyy+.:++yhhsohhhyhdhhdhdddyhddhsoosos++oosoosyysyysoooooooosssyysooo+soyyyyhmNMNmmNmMMNdNmmNdmd:`   ``````````````````...-::///:---.`.---.`.--:/ossssss+::----:::://+oosyhmmyhddhyysoo+++++oossyyyhhdddmmmmmNmmmmddhyoo++/::/:::omNmyyyyhyyyyyyyso+ssso+o/++++oosyhhhhhsyhhhhhhymMMNmNNNNNmmmNmmmmmmmmmmmmmdydNNMNMMd:`.:ommmhsooNMM\n");
    printf("++/////:y:-.:osssosssosssyhd/-`-/:ymNNshdhshhyddyyhyhhddhsossso+oossssyhhyyysoooooooossyyyssosossyhsoohNMmhhdNMMNmmmmmhddh.     ````````````````..-:/+/:-..``..-/+/:--:/+syysssyso/::-:::::///+osyyhhdmmmdhyyo+//////++ossyyhhdddmmmmNNNNmmmddhyys++///:/ymmNmhyyhhyyyysssso+ssosos++++sss+osssssshhhhhsNNNNMNNNMMMMMMMNMNNNNNNNNNNNNNddmmNmhhh-`./smdmhsooMMM\n");
    printf("//+/+/++y+:-:sssossssssyyyhm+-://:smNNhhdyyhhdddhhhhhhdhsossssooooysyshhhyyysooo+++oosssssssysoyyhdyhymNdhdymNNdNNMMNddmmm/`  `````````````````.-:++/:-..```````...-::/+syhhhyyysoo/:::::///++ossyyyoodhdhyys+///::://++osyyhhdddmmmmmNNNNNmmddhyso++//+dNNNNNdhhhdhhhddysso++++ssosss+yhhhhhhhdmdmNNNhoddhsmNNmNNNNNNmydhhhyhhhyhdNmsydmmmhyhy- -/ymmmhsosMMM\n");
    printf("+++++++//:---:/++++++oooshhds/..:/ydmNdmdhshhdmddhmdhdhoossoyssooyyyyyddhyyysoo+++++oooooooohysosyhhmNMmysydmddmmNMMMNNNNNms+/+o-``````````````./+::-.``````````...--::/osyyyyyssso++/:::/+++ossyyhyyhhyyyyso//:::::://+oosyyhhdddddmmmmNNNmmmmddhhyysymmNNNNNdhdhdyyyhddhysssooosssssoshddddddmmmmmmmhhmNhoNNNNMMMMNyysmNhhyhshsyhhd/ymmNmdhhs.`/+hmmdysoyMMM\n");
    printf("++++//+//://++//o+/+//+++sddhy/.-/-+ymdmdyshdhhhhhmddhdyoosyyssoodhhhhddhhyysooo++++oooossoshyyssssydNNmhsosdmmmNNMMMMMMMMMMNNNNh.`````````````-/..--..........-------://+oooossssoo++/::/+oossyyyyydddhhyys+//::---:://+oosyyyhhhhddddmmmmmmmmmdddddmhhdmhhdhydmmdhyyhhhhhhhhyyyhhhhhhhhhyyyyyssssssooooo++ssyyyyyss/osshshysohsyysy/yhdmmdhho--osdmmdysodMMM\n");
    printf("+++++++//o+oooo+sooo++/++ohddhho:..+shddhyhyhyyyyydhhdhsooyysssoyddddddddhhyssooo+++ooosssyyhhddhyssyhyhdyoosdNNNNNNNMMMNMMMMMMNN+`````````````.-..:/osso////////:://+oosssssssssooo+/+::+oosssyyyo+++oooooo+/:::----:://+ooosssyyyyhhhddmmmmmmmmdddmmhhdmmmmmmmNNmdhysyyyyhhyyyyhhhhddhhhhssooooosooooooooooooooo++o++ooooyysosssoo++++++/++++++++oooooooosyy\n");
    printf("++++++++shoyy++/+o++//+oyhdddddhh+`-+dddddmmhddhdhdhddmyosyyssysyhdddddddhhyssooooooossoshdmmmNNmdsymhhhhhyyyymNNMNNNNNmNNMNNNNNNh-````````````....-//o+/..`..`.-.-:+/+syyhhyhhyyso+///-:+sssssyyy+ssoo+++++//:::-----:://+++oooossssyyhhdddmmmddddhhdhhmmmmmdddmmmmmmyyyyhhhyyyyhhhhhdyhhyyssoosss+++++++o+oo++++++oo+++++++++///+oo++o++++++++++++++++++/+++\n");
    printf("//+++++oso+++////++ssossydddddddhh+-oNdmmhyyshyyhhhhhddyosyyyyyyyhdddmdddhhyyssoooooosysshdmNNNNmhydmmmmmmdhhydNNNNMMMMNNNNMMMMNdo+`````````````....--.--..`.```````.`.::/soyhmmds+/:/::+ossssssss++oos++oo+//::--------::////++++oosssyyhhddddddddhhhyshhyyyyyhmmmNNNddddddhhhhhhhhhhhyhhyyssoosssooo++oooosso/+++++++/:////////://///+/://:/://+++ooo+oo:ooo\n");
    printf(":::::/--o---:++/+/:/++://ohddddddhy/+mddd/``...-::///+oosyyhhdhyhdmdmmmddhhyysssooossssysyddNNmhhyydmmmmmNNmmmNMMMNNMMNNNNNNNNNmo::``````````````..............-....-..-:/osyyys+/:-:::+osssssyhsoy+/+++++///::----..-----:::////+++oossyyhhhhhhdhhhhhysy+:-----:::///++++yhhddhyyyyhdhyyysssoo+os++++/////++++/+++++++/://///+oo/++:::::/+/+:////+++:+///://s\n");
    printf("/////:--s/--/oosooooo+++++hmmmdddhh+:+ooo:......--:/++oosy/osyhhdmmmmmdddhhyyssssssssyyssssyhhhyyshdddNmmNNNNMMMMMNNmdhyhddNNNdmo::````````````````..```.....---::::///+oosyyso/:::::/+ossssssyh+yh+/yooo+///::--.......----:::///+++oosssyyyhhhhhhddddyy-/so+//:-::::::-oshhhhhdhhyyyyyyy+/////++/+++///+/++++//++::/://+o+:////////::///://:///+++////++/++h\n");
    printf("/////-:-os/-/ssoooooooo+o+dNNNNNNmdh+/////////-....--::---`` `.:+shmddddhhyyyssssosssyyssssyyhhdhydmmNmmNNMMMMMMNmdysyhhdmmmmNmmyo/``..````````````````````..--::////++oosssso+////++oosssssssss+hoo:ss+o++/::--.........----:::///++ooosssyyyyhhhhhhhhh://osoo+--/mmmo-+yhdhddhhhhyyyssy/:----::-:::::://oyo+o/o+//////:/++////+////:///++++++:o+o+++osooo+/h\n");
    printf("ssoossssss+::+osssssysysyymNNNNMMNNh-------......`````.``  `````.+ymhmddhyyssssooossssssssyddhmmdhmmdhhmNNNNNdhyyyyyyyyyyhdddmddhy+```..````````````````````..--:::////++ooooo++++oossssssoyhss+ooyy++yo++//::--....`.....---::///+++oooosssyyyyyyyyyhhs:y:++/:+-/:++/::ysosyyhyhhyyssss+::y+//+/://:::::+hho++/+////://:+++/oo://++////++:+++++///:++sdhmmy+o\n");
    printf(":::::::--------:://+++oooosddmNMMMNo///+o++///:::::-`  ` ```..``+yydydhhhyssooooooosssooooooooymmddmNmmmddhyyyyyssysssssshddddhssh:````....``````````````````...----:::/+++ooooooossssssso/yhsoooooso/ys+++//::--........---::://++++oooossssyyyhhhddddhoyo///y::s-+/+-oyysssssshyyyssso-/-o+o//::/o::/:/hho++oooo++oooo//+//+///////:////:/++++//++soshNdsooy\n");
    printf("+++++/++/:///++++++++++++ohdddddmNmysshhyshds+++++:`    ``.....`/sys+hyyyysooooooooo+++++++///++ssosyyo+o+oooooooooosssyyyyyssyyyh.``````....``````````````````...---:://+++oooossssssssoo:ohhssossoo/sss/++//:---......---:::///+++oooossssyyyyhhhhdmmmyhy-ohy-oy-/y/:yhdmhhyhyyyysooo:/h-///:+:o/o://:shs:::/:/:::::::////////////+:o+/:::::/:::+oooohNhsyyd\n");
    printf("++++/++++++++++++++o++++:sdhhhddhdysyhhyyydds++++:      ``.-..../hsyshdydhso+/////////++++//:/+/:/++:.../+/+++++oosossssssssyyyhd+````````.....``````` ````````...--:::///+oooossssssssooho/hyyoossos++ys+++///::---------::://++++oooossssyyyhdmNNNNNNNmo+//h/:s+-oy-oydmmddhyyyysooo+:hh:/:/s//y:o/+/+hh///////:::::::++++/-:+///+//////::////+ooohhsshd/dhs\n");
    printf("++oosooo++oooo+++/ooooooohhhhhysyysyyyyyyssssss/-     ````.---.-:oyddhdhddso+//::::://////:::/+::/ooo+`-+/+//+++oossoooossyyyyhdd.`````````...-...```````````...----:://++ooossssyysoos/ydd:yyyhhyooso/ss+o++///:::----::::///+++ooooosssyyhhhdddddmmmmmmhhs:o-o+s/:/:hhdddhhysshhhso+/yhs::ss+:ys:/o+:yds/++++++::oooo//+/:///::::////////++/oy+++sNhsshd+oho\n");
    printf("/+++//////+++///+++++++/odddddddhhhddddddhhhhs.      ````..-::..-ohddhddhds+/::::::::///::--:/o::+soo:`:////+++oooooosssyyyyyhdm/````````````...--......`.....----::://++oosssssssyssyy/osy/ohhmhs+///:ssoyo+/+////::::::////+++ooooosyyyyhyyyyhhdddmmmmmmdy::/+sys:-oyhhhhyyyhhhhsys:ody:/:s+:oho:ss:+hd::::+//::::::/:++/://:oyooo+o++++++++hhs++dmhhhhsy/yo\n");
    printf("/:::::::/o---::://///+++o/osymmddddddddhhhhhh+       ```...`:/...:hhydmdhyo+/::::::::/:::----/o::oyso//////++++ooosoossssyyyyhmy`````````````.....-----------::::////++ooossssyyyyhmmmNs+//:/hyddssooo:osshs+//++++/////////+++ooossyyyyyhhyyyyhhhddddmmmmmh::::/+/-:oosyyyhhdyhhhyy+:y+/o+-++:ho+:s/-yhy+++//+++/:::///ssooooossyhhyyyyyssoosyysoossssyhhyy/o\n");
    printf("/++o++oosh:-:++++++++++++//-/NNNNNNNNNNNNNNmd-      ```..-.`-+-`.:yyyhhhso+/::-::::::::--..--/s/+ys+////+++++o+oossssssyyyyyhhm/``````````````.`....--::://///+++++++oooossssyyyyydmmNNmhhhh/yyhdhyyss++y+o++//soso+/+++////++o+syyysyyyyyyyyyyhhdddmmmmmmmmy/////:::////////+++ooso://osos-/:o+os:+-+hho+o++/+++o/soo+/++/:////:+soosssssyssssssssssssyyyyysy\n");
    printf("+o+o+ooosy::/oooooooooso///-+NMMMMNNNNNNNNNmy`     ```..--.`.//``:syys+:-------::::::---...-:/s+++///+++ooooooososysssyhhyyyhdd-`````````````````......--://+++++ooooossssyyysysyhmmNNNNsshd/shhmmmmmds/yso+////////:+o//////+ohyssssyyyyyyyyyyhdmmmmmmmmmmmmo/+++/+/+oo+o++++++++++///////:///ooo//-hhyooo+///+++/++////::+oo++o++s:o+++/+o+yysydhsdhyyyyyyyy\n");
    printf("oso+oooo++:---:/++oooooos+:/oMMMMMMMNNNNNNNmh`    ```....--.`:/``.+o/-``...-----::-:---...--/+o+ooooooosoosssosssyyssssyhhhyhdh-`````````````````````.....-://++ooossssyyyyysyyyymNmNNNN/::/:ohhmmmmmdh:yydyssssssos/+/://///odhssssyyyyyyyyhyyhhdmmmmmmmmmmmhosoossoossssssssssssssoossoo+ooooooo+++osoo++o++++o++o++///--://::://s/o/++/+soydyohh+hhooss+sso\n");
    printf("///////:::/:://://///////+yhdMMMMMMMMNNNNNNmy`   ```.....-:.`::  ``..```...-----::--....-/+ooosssssossssssssssyysyyssyssyhhhhhh-```````````````.````.......-://+oossssyyyyyysyyyhMMNNNNmsso+//hhdmdddhs-yyoooossyyyys/:::://ommsssssyyyyyyyyhyyhhddmmmmmmmmmmmhyyshhhyhhhhhyhyhhhhyydhddhhhdhdhddddhhhhhhhddddhhhhy+++++//:/://:///+oo/++:+soyhs+ss/yysohh+shs\n");
    printf("+++++/+++/++///++++++o+++oyddMMMMMMNNNNNNNmy.    ``....---/`.-.  ```````...---::///+++ooossoosssysssssysssssssyyyhyssssyyyyhhdh-````````````````...`.......--:/+osssssyyyyyssyyymMMMMNNh/::::/yhsoooo++-ss///::://oy/:::://ohNhsssssyyyyyyyhhhddmmddmNNmmmNNNmmyssyyyyssyhhhyhyyyyyyhdhhhhhdhhhdddddddhddddddddddhd+://+++:o++oo++//o+++/:++/oso+os/ooo+ss+oyy\n");
    printf("..`...----://////++++ooo+osddMMMMMMMNNNNNmd-    ```.-.--::+...  ````````.-:/+oosssyyyysssyyyyyyyyyysssssssyysyysyyyyssyyyyyhhdd/.`````````````.```.......---:/+osssssyyysyyysyyhMMMMMMMNd+---:yh+++ooos-oss++++++oy/:::://+ymNsssssssssyyyhdddddhhhhmNNmmmmNNmmdhhhhhhhhhhdhyhssyyyydddhyhhhyhddhhyhhhhhhhddhhdhhhhy://++::///////+/o/o+o/+o/sss/oo/soo/soo/ss\n");
    printf("``.---.....+-:oo++++oooossssydNMMMMNMNNNNmy`    ```.---:::s/..`````.-/+oosssssyyyyhyyysssyyyyyyyyyyyyyyyyyyhsyyyyyysssyyyyyyhdds-.`````````.`.....`....----:/+ooossssyyyyysyyyymMMMMMMMMMMms/:yhhysooos:+ssoo++/oo/:::://+shMmyssssssssyhddhhhhhhhhdmmmNmmmNNNNmmMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNmmmyysssssssssso++::-:/::++++:/++/+/o++:+o+ooy/oo/soo/ooo/so\n");
    printf("-::-----..:s.-s:-.``.--.......:hNMNMNNNNmm/     ``..---::oho.`.-:+oossssssyyyyyyyyyyyyyyyyyyhhhhhddddhdddhhhsyyyyyyssssyyyyydddh/-..```````.............--::/++oosssssysyssyyyhNMMMMMMMMMMMMNmmdhyyyyhh//o//---:+//::://+ssmMmhyssssssyyhhyyyyyhhddddddNmmmNNNNNmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs///::/:///::::::-://+++++//++/+/o++:+o+oys/oo/ooo/oos/os\n");
    printf("..:/::----oy-:y:-...--........./mMNNNNNmms`    ``....-://yo--/ossssysssysyyhhhdddddddhhhhhhhhhhhhhhhhhhhhyyysyyyyyyyyssyyyyhhddds/-....```.............---:://++osssssssssyyyhmNMMMMMMMMMMMMMMMMNNmmddh/--::---//+:::/+sooyMMNhssssssysyyyyyyyhddddhhhdmmmmNNNNNNmMdyyyyhhhdddmmmmmmhyyyyyyyyyyhNMMMMNso/+++/+++//////+/::://+//+/+///o/o/+s+sdo/oo/oos+oos++s\n");
    printf("```.-//::+hy-:h/---------.-----/hMMNNNNmm/     ``..--://os/+oosssyyyhhhhhdhhhhhhhddhhyyhhhhyhhhhyyyhhhhhhyhysyyyyyyyysyyyyyhhdddho:-.................-----:://+oosssssssssyyhdmNMMMMMMMMMMMMMMMMMMMMNNNdyso//:::/:--:/+ys/hMmssoossyssssyyyyhhdhhhhhhddmmmmNNNNNNmm+++ooossyyhhhdddddddhys++////dMMMMMy++ooooooo+o+++++//:://+:+++++//o/o/+y+ssy/ss/osso+sso+y\n");
    printf(".`  `-/++ydy::+o/o+oooos/.+shmmmNMMMNNmy:`     ``.-::://ooooosyhhddddhhhhhhyyyyyhmdhhhhhhdhhhhhyyyyhhhhhhhhyshyyyyyyysssysyyhddhhy+:--...........-------:::/++oooossssssssyyhhdNMMMMMMMMMMMMMMMMMMMMMNMNNNNmddys+:-:+++yo/hmssssssssssssssyyyhyyhhhhhddmmNNNNNNNNNmoooooooohdmmmmmddmmmmmmddhs++mMNNMMh//////+++/+++++oo+/oo++/+///+//+/s++s+syy/sy/osyo/yyy/h\n");
    printf(". `.:-..-/os/:://+//////-.+/hMMMMMMMNNs.````...--:::://ooooosyyhhhmmhhyyhhyyyyyyhdmdhhhhhhhhyhyyyyyyhhhhyyhysyysyyyysssssssyhddhhyo/:----.......-------::://+++oooooooosssyysoNNNNNMMMMMMMMMMMMMMMMMMMMNNNNNNNNNmdhyys+yo/hhsssssssssssssssyyyyyyhhhddmmmNNNmNNNNNNysssyyssdmmmhddddmmmNmddddhhdmMNNMMs::::://////////////++++++o++++/+/o++y+ohy/ss++sss/yyy/h\n");
    printf("``-:-``````.-/oo/o+ooooo-.sshMMMMMMMNNy-.````..-::://ooooosyyhsyhddmmhhhhhyyyyyyyhmmdhhhhhhyhhyyyyyyyhhhhyhyshysyyyyssssssyyhhdyyys+/:----.....-------::::///+++++++++oooss//hmmmNNNMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNmmmddyshysooooosssssssssyyyyyyyhddmmmmNNmmNNNNNNmhdddddddmmmmmNNNNNNNmmmdddddNNNNMM+:::::::::::::::::://////////++/+/so/s+ohs/so+/sss/oss/s\n");
    printf("`--...```` ``.-::++ooooo--sodMMMMMMMNNs.``....---:+osoooosyyhdyshhdmmdhhyyyyyyyyyhdmdhhhhhhyhhyyyyyyyhhhhyyhsyysyyyyysssssyyhhmhosso/::----------::::::::://////////++++++-:odddmmmNMMMMMMMMMMMMMNNMMNNNNNNNNNNNNNmmmmmmmmmdhhyssoosssssssssysyyyyhdmNmmNNNmmmNNMNNmdddddddhdyydmmmmdhhhhhhhhhhdNNNNMN:::::---:---:-::::::::::://///////so/so+ss/oso/sss/osy+s\n");
    printf(".....````````````--://os--oodMMMMMMMNh....`.`..:+osssoooysyydmdsyydmmmhhyyyyyyyyyyhmmddhhhhhhhyyyyyyyyhhhyyhsyysyyyyssssssyyhhdmy++++/::---------::::::::::::::::///////:.:+yyhhdmNNMMMMMMMMNMMMMNNNNNNNNmmNNmmmmmmmmmmmmmmmmdddhysossssssssyyyyyhdmNNmNNNMNmmmNMMNNdho+ohhhy+odmmNdo//////////hNNNNMm:::::::::-------:--::::::::::::///so/y++ss/oss/sss/+ssos\n");
    printf("``.````.````````.......-.:+hdMMMMMMMNd-.`` `.:+ossssooshsyyydNmysyhdmmdhhyyyyyyysyydmmdhhhyyhyyyyyyyyyhhyyyhsyysyyysssssssyhhdmmmy+:-:::---------:::::::::-----::::::::.-//oyyyhdmNMMMMMMMMNNNMMMNNmmmmmmmmmmmmmmmmmmmmmmddddddddddhssossssssyyyhdmNNNNNmMMMNmdNMMNNmh+++shdy++smNNyo/////////+hNNNNMh::/::::::::::::::::::::::::::::://oo/s++yy/oss:syh+/ssos\n");
    printf("`.``....   ````-....-.-.:+oyhMMMMMMMNm:```./ossssysooyysssyhdNNhsyhdmmdhyyyyyyyyssyhdmdhhhyyhyyyyyysyyyhhyydsyysssssssssssyhddmmNds/.``.----------::::-----.---------..:/::syyhhdmNMMMMMMMMNNNMMMNNmmmmmmdddddddddddddddddddddddddddddysooosyyyhdmmNNNNmMMMNmdmMMMMNmd+++oydhsymmmNy+++++++++++yNNNMMy/////////////::::::::::::::::::///oo/y++ys/+yy:oyyo/yyso\n");
    printf(".```...```.`.-:------:-+++oyysyhyyyho/:/+shhsyyyyooyyssssyhmMMdsyyhdmdhyyyyyyyysssyhdmdhhyyhyyyyyysyyyyyyyhssssssssssssssyhdmmmmdhs:.`````.------------.............::::- osyyhhdmmMMMMMMMNNmmNMMNNmddddddddddhddddddddddhhhhhhhhhdmmdddhysoyhhdmmNNNNmNMMNNmNMMMMMNmh+++oydmmmmmdmmhs++++++++oyNmmMMy+++++/+///////////////////////:++:oo/y+/ss/+yy:+yyo/syso\n");
    printf("--------...-----::------::/:+++//+ooo++syhddyydhsosyssssssyhmMMNssyhdmdhyyyyyyyysssyhddddhhyyhyyyyyyyyyyhyyhsssoosssssssssyhdmmdhddds:.```` ``````.....`````````..-:::--./yyyyhhdmNMMMMMMMNNmmmNMNNmddddddhhhhhhhhhhhhhdhhyyyyyyyhmmmdmmddhyhddmmNNNNNMMNNNNNNMMMMMNdhyysymmmNNNmmNNNNho++++++ohNmmMMs+++++++++++++///////////////////o:+o/y+/ys/+ss/+hys/oyy+\n");
    printf("-:::--::.--------::::::-----::::+//++shdddhyyhhyyosssssssyyyhNMMysyyhdhhyyyyhyyyssssyhdddhhhyhyyyyyysyyyhyyhsssoosssssssssyyhddddddmms:.````````````````````...-------..:yyyyyhdmNNMNMMMMNNmmddNMMNmddddhhhhhhhhhhhhyyhdhyyyyyyyyhNNdddNmddhddmNNNNNMMMMNNNNNNMMMMNNmdysymNmmNNNMNMMMMMNho++++ohNmmMMs+++++++++++++++++++++++++++++++/+/+o/y+/ss/+sy/+yyy/+yy+\n");
    printf("-::::-::---::::///:::::-------::+:+oyddmdhyyhysyyysossssyyyyhmMMhsyyhhhhyyyhhyyyssssyyhdmdhhyyyyyyyyyyyhyhyhsssosysssssssssyyhddhddmmmy:.```````````````````.........``/yyyhyhddmNNmNMMMMNmmmddmMMNmdddhhhyyhhhhhhyyyyyyyyyyyyyyhdMNmddmNmdddddNNNNMMMMMMMMMMMMMNNmNNNNNNNNNdNhdMMMMMNNmNmhhhhdNNdNMMo+++++++++++++++++++++++++++++++++/+s:yo/sy+/yy+/ysy/+hy+\n");
    printf(":-:::/:/::://///++//::---:/-:-::++shdmmmhhyyssyyyyoossssyyyhdmNMmsyyhhhyyhhhhyyyssossyhhdddhhyyyyyyssyyyyyhhsssssyssssssosssyhddddddmNmh/.```              ``````````.+yyyhhhhdmmmmmNMMMMNNmddhdNMNNmdhhhyyyyhhhyyyyyyyyyyyyyyyyhNMNmdddNmdmNdddNMMMMMMMMMMMNNmmddmNNNNNNMMMNNNNMMMMMNNMNMMMMMMNMMMMN+/++++++++++++++++++++++++++++++++//s:hs/ss+/yyo/ssy+/yh+\n");
    printf(":::-/:://///++++o++++/::://///+/+shddmmdhhsosyyyyooosossyyyhdmmMNsyyhhyyyhhhhhyyssosssyhdddhhyyyyssssyyyyyhhsssssssssssoossyhdmNNNNNmNmdho-``                 ```.../syyyyhdyhdmmmmNMMMMMNNmddhdmMMNmdhhyyyyhhhyyysssssysssyyysymMMNmddmmdhmNmdddmMMNmmmmmmdddhddmNmddmmmMMMNNNNMMMMMMMMNNmmmmNNMMMMN//////++/++++++++++++++++++++++++s//s/ys/sy+/sso:syho/yho\n");
    printf("///::/++//+o+++oooooo++////+++++syhdmmmdhyoossyyy++syyossyyhdmmNNssyhhhyhhhhhhysssosssyhdddhhyyyysssssyyyyyyossssssssooshdNMMMMMMMmhdNmddds/.`` `       `````````..+yyyyyyyhyhdmNNNNMMMMMNmddhhhhNMNNmhhyyyyyhhyysssssssssssssydNMMNmddmmddNNmddmmmNNmdhhhhhdddddNNmyyyyyhmNmmNmhmhmMNNNNy::/:sdNmNMm//////////++++++++++++++++++++++ohs+s/hs/yh+/yhs:syys/sh+\n");
    printf("/////:/+++++oosoooo+++oso//++/+shhdmmmmhysosoossso+syysyyyhhdmmNMysyhhyyyyhhhhyyssoossyhhdddhyyyysssssyyyyyyosssssoosymNMMMMMMMMMMysdNmmmhys/-```        ````..`.-syyyyyyyyyymmmNNNNMMMMMNmddhhyhdMMNmdhyyyyyhhyysssssssssssyyhNMMNmdddmmdmMNmmdmNmdmddhhhdddddmmNNNy+++++yNyssoosoosyyys+++++smNdNMd://///////+++++++++++++++++++++++syyysys+hdo/hdh:odhy:oho\n");
    printf("+/+oo+////++///://///////:-::/syhhdmmmdhyssyoooooo+syssyhdhdmmmmNhsyyhyhhhhhhhysssooossyhddddhyyyssssssyyyysooooosydNMMMMMMMMMMMMMyshNmNmdhyy+:.`       ``....../y-.-hyyyyyyhNNNmNNNMMMMNNdhhhhyyhNMMNdhhyyhyhhysssssssssssssymMMMNmdhdddmNMNmdhdmmdmdhhhhhddmmNMNNNdoo+++sms+oooosoossssssoo+hNmhNNh++//////////++++++++++++++++++++++//syyhhhhyyyyy+ohdh/ody\n");
    printf("o++//::::::::::::::::-::::::/syyhdmmmmdhyssyysooooosssssyhmmmNmmNdsyyyyyyhhhhhyssooooosyhhdddhyysssssssysyyyoshdmNMMMMMMNNNNNMMMMMNhhdmmmmdmmy+/-``   ```.....-oys//yhyyyyyyydNMMMNNMMMNNmmdhyhysydMMNmdhhhhhhyyssssssssssssydMMMNmddddddmMMNdhhhdmmmNhhhddddmNMMNNNNNNNNNNNmmmmmmmddddddddddmNNNNMmoossoo++//////++++++++++++++++++++/-/s+/oydhhhdhhhhhyyyyyh\n");
    printf("----.::/::::::::::::::::://+syyyhddmmmdhyyysyysoooossssyyhdNNNNNNdsyyyyhhhhhhhysssosoosyyhdmdhyyyssssssssyyyyydmmmmmmmdhhdddmNMMMNmmddddmmmmmmh//:.````...--.:yyyyyyyyyyhyhyyydMMMMMMMNNmddhyyyssshMMMNmdhhhhhyssssssssssssydMMMNNddddddmNMNmhyyyddmmNNdddmmmNMNNNNMNNMMMMMMNMMMMMMMMMMMMMMMMMNMMMmysooossoooo+++/////+++++++++++++++/-/so+++sh+shy+++oossyyyh\n");
    printf(":::--///::::::////::/::::/syyyyyhddmmmmhyyyyyyssooooosssyhdNNMMNNdsyyyhhhhhhhyysssssoossyyhmdhyyysssssssssyyyyyyyyhyyyyyyyyhdmNMMmdddddhhddmmmmh/::-``..--..+yyyyyyyyyyyyhhhdmNMMMMMMMMMNNmmmmmmNNMMMMNmddddhhyyssssssssssshNMMMNddhddddmMMNdhyyhyhdmNMNdmmmmNNmmNNMNmNNNMMMMMMMMMMMMMMMMMMMMMMMNhysssssoooooooooo++++//++++++++++++/-:+o+++++oso+++++++++++/s\n");
    printf("/::-////::::::://///://:/syyyssyhhdddmmdhyyyyyyyso+ooossyyhmNMMMNmsyyyhhhhhhhyysssssooosyyhdddhyyysssssssyyyyyyyyyyyysyyyyyyhhmNMNmdhddhyyyhdmmdh/:-:---:--syyhhhhyyyyyyhdNMMMMMMMMMMMMMNNNNNNNNNMMMNNNmddhhhyyssssssssssyhmMMMNmdhddddmNMNmdhddyyhhmNMMmdddmmddmNMNNy+++syyyyhhhhhhhhhhhhhhhhhyysoooooooo+++++++++++++++++++++++++/-:o+//////+++++++++++++/-y\n");
    printf("//:-///::::::::/::://:/+syyyyssyyhdddmmdhyyyyyyysso+oossyyhdmMMMMNyyyyhhdhhhhyysssssooossyhdddhyyssssssssyyyyyyyyyyyssyyyyyyyhdmNMmdhhhyyhhhhddmmh//:://:/yyyyhyyyyyyhmNMMMMMMMMMMMMMMNNmmddddmmmmmmdddhdhhhhyyssssosssssymMMMNmdhhddmmNMNNmddhhyyyhmNMMNmdddddmNMNNNy+++++++++++ooooooooooooooooooo+o++++++++++++++++++++++++++++/-:oy+++++++++/:::///++oo:-y\n");
    printf(":/-://::::::::::://///+yyhyyyssyyyhhddmdhhyyyyyyyssooosssyhdmNMMMNyyyyhhhhhhyyyssssssooossyddddyyyssssssyyyyyyyyyyyysyyyysssyhhdmMNdhhhyyyhhhyyhdmh++//:shyyyyyyyhdNMMMMMMMNNNMMMMMNNNmmmddddddddddhhhhhhdhyyyssssosssssydMMMNmddddddmmMMNNNmdhhyyyhmMMMNmddddmNNmddhs++++++++++oosssys+++++++ooooo+++++++++++++++++++++++++++/++/-:oy++++++++oyh++++/++///-:d\n");
    printf("//-///:::::::::::::/:+yhhhhyyssssyyhhdddhhhyyyyyyyysooossyhdmNMMMNyyyyhhhhhyyssssssssoooosyhdddhyyyyssssyyyyyyyyyyssyyyyyysssyyhdNMmdhhyyyyhhhhyyhds+++hdhyyyhdNNMMMMMMNNmmmmmNMMMNmmmddddhdhdddddhhhhhhhhhyysssssossssyhNMNmddmNmmdmmNNNNMNmdhyyyyhNMMMNNmysoo++++++oooosssssyyyyyhyhdds++++++++++++++++++++++++++++++++++++++++::+y+++++++++oyd+++++++++:-/d\n");
    printf("/:-///::::::::::::::oyhhhhyyyssssyyyhhhhhhyyyyyyyyyysoossyhdmNMMMMhyyyhhhhhysssssssssoooosyyhddhyyyyysssyyyysyyyyyysyyyyyyssssyhhmMNmhhyhhyyhhhyyshhsymmdhhdmNMMMMMMNmmdddhddmMMMNmdddhhhhhhhhhdddhhhhhhhhyyysssssssssyymMMNmNNMNmmdmNMNMMNNmdhhyyymMMMMNNNs+oooooooooooooooossyyyyyhhhhho++++++++++++++++++++++++++++++++++++++::+s++++++++///+s+///////:--/s\n");
    printf("/-://::::::::::::::oyhhhhhyyyyssssyyyyyyyyyyyyyyyyyyysossyhdNMMMMMhyyyyhdhysssssssyysssooossyhdhyyyyyysssyyysyyyyyyysyyyhyssssyhhdNMmdhyhdhyyhhyysshhNMNNNNMMMMMMMNmddhhhhhhdNMMMmdhhhhhhhhhhhhhhhdhhhhhhhhysssssssssyhmMMMMMMMNmddmNNMMMNNmdhhyyydNMMMMNNNd++o+o+oooooossyhhhdddhddddhhhy///+++++++/+/////++++++++++++++++++++::+s+//:::---------------------\n");
    printf("/-:///::::::::::::+yyhhhyyyyhyysssyyyyyyyyyyyyyyyyyyyyoosyhmNMMMMMdyyyyhhhyssssssyyyssss+ossyhhhhyyysysssyyyssyyyyyysyyhhyyssssyhdmMNdhyyddhyyhyyyoohdMMMMMMMMMMmmddhhhhyhhdmMMMNmdhhhhhhhhhhhyhhhhhhhyyhhyysssssssssydMMMMMMNNmmdmmNNNMMNmdhyyyydmMMMMMNNNmsooosyyyyyyyhhhhhdddddddddddhh///++++++++:-/++++++++++/+++++++++++/:/+:------:-::::::::::::::-:::-\n");
    printf(":-://::/:::::--::+yyhyyyyyhhhysssssyyyyyyyyyyhhyyyyyyyoosshmNMMMMMdyyyyhhhysssssssyyysssoossyyhhhhyysyssyysyyysyyyyyyyhhhyysssssyhdNMdhyyhddhyyyyysoshmMMMMMMMNmddhhyyyyhhhdmMMMNdhhhhhyyhyhhyyyhhhhddhhhhyyssssssssydNMMMMMNNmddmNNNNMNmmdhyssyhmNMMMMNNNNmdysyyyyhdhhyhhhhhhddddmmmdddhd+/++++++++/-:/+ooooo++++++++//////+/-----::::///+++++++sy+++++:-/soy\n");
    printf("--::::::::::---:+yyhhhyyhhhhyyssssssyyyyyyyyyyhyyyyyyys+osydNMMMMMdhyyhhhhysssssssyyssyys+ossyhhhhyyyyyssyyyyyysyyyyyyhhhhyyssssyyhmMmhyyhdmdhyyyysoosdNMMMMMNmddhhyyyyyyhddNMMMmdhhhhyyyhyyyyyyhhhhdddhhhyssssssssyhNMMMMMMNmmmNNmmNMNmdhyysshdmNMMMMMNNNNmdhyhyyyhdhhyhhhhddmddmmmmmmdhd++++++++++.-/++++ooooooo+++++/////::--::://++++++++++++oho++++--+s+h\n");
    printf("-::::::::::----/syyhyyhddhhyyyyyyyssssyyyyyyyyhyyyyyyssoosyhdNMMMMmhhyhhhhyssyysssyyyyyysooosyyhhhhyyyyyyyyyyyyyyyyyyyhhhhhysssssyydNNhyyyhmmdhyysssooymMMMMMNmddhyyyhyyyhddNMMNdhhhhhyyyyyyyysyyhhhdmdhhyyyssssssshmMMMMMNNmmmmmmNMMNmhyyssyhdmNNMMMMNNNNmmddyyyyyhhhyyhhhddddmmmmmmmddhd++++++++++.:/+++++++++++ooo++++++///::///:::::::://///++ssooo/-/sooh\n");
    printf("--:::::::::---:osyyyhdddhhyyyyyyyyssssyyyyyyhhhhhyyysssoosyhdNMMMMNdhhhhhhyyyhhyyyyyyyyyys+ossyyhhhhyyyysyysyyyssyyyyyhhhdhyysssssyhNNdyyyydmmhhyyssooodNMMMMNmddhyyyhyyhddmMMMmdhhhhyyyyyyyysssyyhddddhhyyyssssssydMMMMMMMNmmdmNMMNmdhysssyhhmNNMMMMNNNNNmdddyyhyyyhhyyhhdddddmmmmmmmmdhdo++++++++/.:+o+++++++++++++++++:/:::/++///:::::-------------:--:///o\n");
    printf("---:::::::----+syyhhdddhhyyyyyyyyysssssyyyyyhhhhhyyyssso+osydmNMMMNmhhhhhhyyhdhhyyyyyyyyysoosssyhhhhhyyysysyyyyyssyyyyhhdhhyyyssssyhmNdhyyyhdmdhhyysooosNMMMMNmddhyyyhyhdddNMMNmddhhyyyyyyysssssyyhdddhhhyyssssssyhNMMMMMMNmmNNMMNmdhyyssyyhhdmNMMMMMNNNNmmdddhhhyhhhhyhhdddddmmmmmmmmmdhdo++++++++/-/+o++++++++++++++++-.-::/++++++++++////::::--------------\n");
    printf("---:://:::---/syyhdmddhhyyyyyyyyyssssssssyyhhhhhyyyyssoo+osyhdmMMMMmdyyhhhyyddhhyyyyyyyysoooossyyyhhhhyyyysyyyhyyyyyyyhhhhhhyyyssssydmmhyyyyydmmhhyyoooohMMMMNmddhyyyhhddhdMMMNmdddhyyyyysssssssyyhdddhhhyyssssyydNMMMMMNMNNMMMNmdhyyssyyhhdmmNMMMMMNNNNmmddhdhhhhhhhhyhhhddddmmmmmmmmddhdo++++++++/-/+o+++++++++++++++:.-::/++++++++++++++++++++++++/::/::::-\n");
    printf("----://:::---oyhdmmdhhhyyyyyyyyyyysssssssyyyyhhhyyyyssso+ossyhmMMMMNdhyyhhyhddhyhyyyssssoooooossyyyyyyhyyyyyyyyyyyyyyyhhhdhhhhyssssyhmmhyyyysydddhhysooosNMMMNmddhyyyhhdhdmMMMNmddhhyyyyssssssosyyhhhhhhhyysssyhdNMMMMMMMMMMNNmdhyysssyyyhddmNMMMMNNNNmmdddddhhhhhhhhhhhhhhdddddmdmmmmddhd+++++++++/-/+o++++++++++++++:.-::/+o+++++++++++++++++++oooo+-/sooooo\n");
    printf("----://::::-/yhdmmdhhyyyyyyyyyyyyyssssssssyyhhhhhyyysssoo+osshNMMMMMmhyyhyhydmdyhhyysyssooooooossyyyyhhyyyyyyyyyyyyhyyhhdhhhhhyssssyhdmhyyyssyhddhyhhsoosdMMMNmdhhyyyhhhhdMMMMNmddhhyyyssosssossyyhhyhhhyyyysyydmMMMMMMMMMMNmdhyyyssssyhhdddNMMMMMNNNmddddhhhhhdhhhhyyhhhdhdddmmddmmmdddhdoso+++++++-:++++++++++++++++..::/+++++++++++++++++++++ooooo/:osoosss\n");
    printf("---::/::::::yhdmmddhyyyyyyyyyyyyyyysssssssyyhhhhhhyyssooo+oosdMMMMMMmdhhhhddNNNmmmhyyysssoooooooosysyyyyyyyyyyyyyyyhhhhhdhhhhhyssssyhmmhyyysssyddhyymyooohMMMNddhhysyhhhdNMMMNmddhyyssssssossossyyhhyhhyyyyyyydmMMMMMMMMMNmddhyyysyyyyyhhhdNMMMMMNNmmdddddhhhhhdhhhhhhhhdhhhhdmmmmmmdddhhhyhdyo+++++-:+++++++++++++++-.-::++++++++++++++++++/////////--//////+\n");
    printf("---::::::::oydmmmmdhyyyyyyyyyyyyyyysssssssyyhhhhyyyyssoooooosdMMMMMMNmddmmNNMMMNmhyysssssoooooooosssyyyyhhysysyyyyyyhhyhhhhyyyyysysshmdysyysssyhhyyydhssosmMMmddhyysyhhhmMMMMNdhyyyssoooooosoossyyyyyhyyyyhhhdNNMMMMMMMMNmdhhyyyysyssyyhhdNMMMMNNNNmddddddddhhhhhhhhhhhhhhhddmmmmmmddddhhh+oydhyoo++::/+o++++++oo+++/`-::/++++++/////::::::-------------------\n");
    printf("---:::::::/yhdmmmmdhhyyyyyyyyyyyyyysssssssyyyhhhhhyyysoooooosdMMMMMMMmdddmNNMMNmdhyssssssoooooosssyyyhyydhsshsyyhyshydshhyhyhyyysyssyhhsssyssyyhyyyyhhysoshMMmhhyyyyyyydNMMNNdhhyyossoooosossossyyyhyhhdhhdddmNMMMMMMMNmmdhhyyyyssssyyhhdNMMMMNNNNmddhddddddhhhhhhhhhhhhhhhddmmmmdddddhhdsooosyhhyo+/-/+++ooooooooo+..-:/++++/:::::::::::::::::::://::////::::\n");
    printf("----::::::oyhdmmmmddhhyyyyyyyyyyyyssssssssyyyhyhhhhyyssooooosdNMMMMMMmddmmNMMMNmdhyyyysssoooooossyyhdhydddhhdyhhhyyhddhddydhdyyhyysyshysssyssyhyyyyhhhssoodMMdhhyyyyyyhmNMMMNmddyssyyssssssyyyyhhddddmmmmmNmNMMMMMMMNNNmddhhyyyysssyyhhdNMMMMMNNmmddhddddhddhhhhhhhhhhhhddhddmmmmmmddddhdoooooosyhdyo-:++oooooooooo/`-::/+/:::::::://///+++++++ooooo+oysssoooo\n");
    printf("-----::::/sshdmmmmmddhyyyyyyyyyyyyyyyysssyyyyyyyyyyyyysoooooshNMMMMMmmdmmNNMNNmdhyyyyyyyssoooossssyhhyyhddhyysyhhyhhmmdmddddddhhhhhhyhhssyysyhhyyyyhhhysoodMMmddyyhhhhmNMMMMNdhyysssssoosssssyyhddmmmdmmNNNMMMMMMMMNNNmddhhyyyyysssyhhmNMMMMMNNmmdddhhddhhhdhhhhhdhhhddddhddmmmmmmddddhhyoooooooosyhho//+oooooooooo-.::/+/::////+++++++++++++oooooo+oooooooooo\n");
    printf("-----::::+ssyhdmmmmmdhhyyyyyhhhyyyyyyyyysyyyyyyyyyyyyyssooooshNMMMMMdyyyhhhhddddhyyysoshhsoooosssyyyhyyhdmdhssshhyyhhddmdhhhdhyyyhdyyyysyhyyyhhhdhdddddhssdMMNmdddmddmMMMMMNdhyyssssosoosssyyyhmNNmmmdmNNNMMMMMMMMMMMMMNNNmmmmmmhysyhmNMMMMMNNmmdddhhhhdhhhhhhhhhhhyhhhdddddmmmmmmdddhhysssssssooo+oyyhy+ooooooo++:::://///++oo++///++++++++ooooooo++ooooooooo\n");
    printf("------:::ossyhhdmmmmmdhyyyhhdddhdddddhhyyyyssyysyyyyyyyssoooshmMMMMMmhyyyyyddmmmhyyssooshhsoossssyyyyyyyydhyyssyyshhyhddmdhhhhyyhhhyyyssyyyyyyyhhyhdhdhysymMMNmdddmhmNMMMNmdhyyooooossssyyyhhhdmNmmddmmmmNMMMMMMMMMMMNNNNNmmddhyyssyhNMMMMMNNmmmdddhhhdhhhhhhhhhhhdhhhdddddmmmmmmdddhhyssssssssooo+++oyhy+oooo+///////+++oo++ooo+//++++++++ooooooooo+ooooooooo\n");
    printf("--------+sssyyhhdmmmmmdhhhyhhhhhhhhhhhhhhyyssssssyyysyysssoooymMMMMMmhyyyyydmNmmhhysooooooosssssyyyysyyyyhhhhhhyyydmyyhdmdddhhhyyhhyyysyhhyyyyyyhhhddyyysydMMNddddddNMMMNdhyyssoooooooosyyhyyhdddddhdmNNMMMMMMMMMMMMMNNNmddhhyyyssyhmMMMMNNNmddddhhhhhhhhhhhhhhhhhddddddddmmmmmmdddhhysssssssssooo++ooshm+oo+//+++++oo+oo++++ooo++//++++++oooooooooooooooooooo\n");
    printf("----.../ososyyhhhdmmmmmddhhyyyyyyyyyyhhhyyyyyyssssssssyyssooshmMMMMMmdhyyyhdNmmdhyssooooosssssyyysyyyyyyhddddhhyyymdssyhdmmddhhhyhhyyysyhyyhyyyyyyhhdyhhyymMMNdddddmNMMMmdhyysooossooosyhhhhhdmmNNmmNMMMMMNMMMMMMMMMNNNmmdhhysssyyhmMMMMNNNmdhdhhhhhhhhhhhhhhhhhhhdmddddddmmddddddhysssssssssssoo+++++oym++++//+++oo+++oo+++++ooo+/++++++ooooooooooooooooooooo\n");
    printf("....-:+osoosyyyyhhdddddddddhhhyyhhyyyhhhyyhhhyyyssssssssssssydNMMMMMmdhyyhdmmmddyysoooooosssssyyyyyyyyyhhdddddhyhhmdssyhhdmmmdhhhhhyyssyyyhhyssssyyhhyhdyymMMNdddddmNNNNmdhysoooososssyhhdmmmNNMNNNNMMMMMNmMMMMMMMMMNNmmdhhyyysyyhNMMMMNNmmdhhhhyhhhhhhhhhhhhhddhddmdhddddddddddhysssssssssss+/++oooo+ohN++//:::::::://+++++/+oooo+++++ooooooooooooooooooooooo\n");
    printf("-:://+sosoosyyyyyhhhhhhdddhhhhhhhhhhhhhhhyyhhhhyyyysssssssyydmNMMMMMmdyyyhdmmmdhysoooooosssossysssssyyyhhhddddhhhyNdsssyhddmmdhhhhhhyssshyyyyssssyshyyhdyhNMMNmmmmmmmNNNmhysooooososysyhddmNMMMNNNMMMMMMMNNMMMMMMMNNNmmddhyyyyyhmMMMMNNmmdhhhhhyhhhhhhhhhhhhdhdmdddmmdddddddddhysssssssssooos:+oosooo+shm+/::::::::://////////+oooo+++oooooooooooooooooooooooo\n");
    printf("//++osossoossyyyyhhhhyhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyysssosshdNMMMMMmhhyyhdmmmdhssooso+oosssssssssssyyhyhhddddhhhhNhsssyyhhdddddhhhhyssyhhhhyyyyyyyyyyhhyhNMMNmNmmmmNNNmdysoooooossyyyhddmNMMMMMMMMMMMMMMMMMMMMMMNNNNmddhhyyyydNMMMNNmdhhyyyyhhyhhhhhdddddddmmNmdddmmddhhhhhyysssssssssss+sss//+osooooyym++//:::::/:///+///:::/+++++++++oooooooooooooooooooooo\n");
    printf("+oooosossoosssyyhhhhyyhhhhhyhyyhhhhhhhyyyyyyyyyyhyhhyyyyyssoshmNMMMMmhyyyhdmmmdysosssoo+osssoossssyyyyyyyhhdddhhhdNhssssyyhddhddhhdhyssyyyyyyyyyyyyyyyhhyhMMMNNNmmmmNNmdhsooooossysshhdmmNMMMMMMMMMMMMMMMMMMMMMMMNNNmdddhyyyymMMNNmdhhyyyyyhyhhhhddmdmmmmmmmmNNmmddddmdhhyssssssssssssssooyys:/+/+/+ooyym++//::////////+/////::+////////////////+++++++++ooooo\n");
    printf("ooooooosssosssyhhhhhhhhhhhhyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhysssydNMMMdhysyhmmmdhsoosooooooosossssssssyyyyyhhddddhhmNhsssssyyhddhddddhyssyyyyyyyyyyhyyyyhhydMMMMNNmmmNNmdhysooooossysyhmmNNMMMMMMMMMMMMMMNMMMMMMMMMNNmmdhhyyyhmNNmdhhyyyyyyhhhhdmNNNMMMMMMMMNNNMNmmdddddmyssssssssssssyyssosyys/+//++/:://+///////////+++/////::+oo+++++++//////////////////////\n");
    printf("+/ossosssssossyyhhhhhhhhyhyyyyyyyhhdhddddddhhddddhdhhddddddhyssymMMNhyssyhdmdhysooooooooooosssssssssyyyyyhhddddhhNmhssssssyhhhhdddmdyssyyyyyyyyyhhhhyyhhymMMMMMNNmmNmdyyssooosoyyhyydmNMMMMMMMMMMMMMMMm+syhsmNNNNNmmdhhyhyydmddhyyyyhhhhdmNNNNMNNNNNNNNMMMMNMMNmmmmmddddsssssssssyyyyyyooyyyo/+o+/++/:::/::----::::///////////syyyyyyshysssoooo+++++//////////\n");
    printf(".+ssoossssoossyyhhhhhhhyyhyyyyyhdmmmmmmmmmmddddddddddddddddhhysymMMmysssyhdddhyssoooooooooossssssssssyyyyyhdddhhdNmhysyysssyhddhhdmdyysyyyyyyyyhddhysydhhNMMMMMNNNNmdhyssooossohhhhdmNMMMMMMMMMMMMMMMMd//://+dNNmmdhhhhhhhhhdhhhhddmmNNNmddmmmmmmmmmdmmmmmmmNNNmmmmmmddddysssyyyyyyyyysosyyyo+++++++/:::/:--:----:://+++//////yyyyysshmyyyyyyyyyyyysssssoooo++\n");
    printf(":sssosssoooossyyyhhhhhyyhyyyhhdmNMNNNNNNNNNmNNmmddddddddddddhyhmMMMmsssyhddhhhyssooooooooosssssssssssyyyyyhdmdhhmNmdhsyhysoshhhdhhmdyyyyhyyyyyhhhhhyshdhhMMMMMMMNNmdhyysoooosyshdddmNMMMMMMMMMMMMMMMMMh+oo//+ymmmddhhhhddddddmNNNMMMMNdhhddmmmmmmmmmddddddddddmmmmmmmdddddhsyyyyyyyssoooyyyy+/++////:-:::----::::-:::////////+yyyyyysmhyyyyyyyyysyysssssssssso\n");
    printf("ossoosssoooossyyyhhhhhhhhhhddmNMMMMMMNNNNNNNNNNNNNmmmmdddddmmmNMMMNhyssyhhhhhyyssooooooooosssssssssssyyyyyhmdhhhNNmdhsyhyssoyhhdddmdyyyhhyyyyhhhhhhyyhhydMMMMMMMNmdhyssooossydydmmmNMMMMMMMMMMMMMMMMMMd/+o//ohmmdddddmmNNNNMMMMMMMNNdyyhdNNNNNmmmmmmmmmdddddddddddmddmmdhsshsoo+//::-:osyyys/////://:-/------------:-:::::::-:::::+yhhsyyyyyyyyyyyysysssssoooo\n");
    printf("sososssooooossyyyyhhhhhdddmmNMMMMMNNNNNNNNNNNNNNNNNNNmmmmmNNNMMMMNdhysyyyhyhhhysssoooooooossssssssssyyyssydddhhhNNmdysyhhysooyhhdmmhyyyhhyyyyhyhhhhyyhhydMMMMMMNmdhyyssoossyhdhmNmmMMMMMMMMMMMMMMMMMMMN+/+/+ydmmmdmNNNMMMMNmddhhyyyyyyyhmNNNNNmmmmNNNNmmmddddddddddddmds+++////:/:::-/ssyyyy////////::::-----.--.-.::::-:::/:---..ssd.---:+syyyyyyyssssssoooos\n");
    printf("oooosssooooosyyyhhhdhhdmmmNNNMMNNNNNNNNNNNNNNNNNNMMNNmmmmmmmNMMMMmhyyyyyyyyhhhyssoooooooooossosssssyyssssydddhhmNmmdyyyyhhysooyhdmdyyyhhyyyhhhhhhhhyydyymMMMMMMNdhyyssoossyhmdmNNNNMMMMMMMMMMMMMMMMMMMMo/++hmmNNNMMMMMMNNmddhyyyyyyyyyyhmmmNNNNNNNNNNmmmmmddddddddddmms//++/+/::::::::osyysh+////////:::--. ----..-----.::--::/:::/od+::.`.--/oyyyysssssooossy\n");
    printf("soosssoooooosyyyhhdmddmNNNNNNmNmmNNNNNNNNNMNNNNNMMMMNNNmmmmmNMMMmhyyyyyyyyyyhysssooooo+ooossssssssyysssyyhddhhhNNmddhyyyhhhyoosyhdhyssyhhyhhhhyyyyyyhhyhNMMMMMNmhyysssosyhddNdNNNNMMMMMMMMMMMMMMMMNNmdyo++mNNNMMMMMNmmmmmdddddhhhhhhhyyhhhhdmmNNmmmmmmmmmmmddddddddmmy++/+///+:/::::::/++sshs////+///:::::-:---..--..-:-.-::::::-yys. `:`.`-.``:oyysssssssysys\n");
    printf("ooossosooooosyyhdmmmmNNNmNmmNNNNNNNNNNNNMMMMMMMMMMMMMNNmmmmNNMMNyhhhyyyyyyssyyssssoooo+ooossssssysyyyyyyyhdhyhdNmddhhyyyhhhysooyhhhyssyhyyhddhyhhyyyhhyhMMMMMMNdhyssssssyddmNdNNNMMMMMMMMMMMMMMMmsooosss/yMMMMMMMNNNNNmmddhhhhhhddhhhhyhhhhhhddmmNmmmmmmNNNmmddddmmmd++++/+/////////:::///++o////++//+o+//:/.---   `--.-:----::-+yy:` .``-`  . .:ssssssssyyyhs\n");
    printf("oossosooooossyhmNNNNNmNmmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMNNmmNNMMMdyyyhhyyyyysyssosssooooo+oosssssyyyyyyyyyyhdhhyNmmdhhhhhhhhhhyooyyhysssyhyyhhdhhhhyyhdhydMMMMMNmhysssssyhddmNmmNMMMMMMMMMMMMMMMmyosso+so//smMMMMMMNmmmddddddhhyyyyhhddddhhhhhhhhddmmNmmmmNNNNmmmmdmmm++///+++++/////////////+o/+//++::/o+////--`--....``....---..oy+-    --` .-::osssssyyyhyhyo\n");
    printf("oosoossoooosyhmNMNNNNNNmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNMMMNhyyyyhyyyyyssssoosoooooo+oossssyyysyyyyyyyhhyhhNddddhhhhhhhdhhsosyyysssyyyyhhhhhhhyyhhyymMMMMMNdyyssssyhdddmNmNMMMMMMMMMMMMMMNmmhoso///+osoymNNmmddddddhhhhhyyyyyyyhhhdddddhhhyhhhdddmmmmmNNNNmmmmmmy/+/++++++++///////////////+/+++::/+////:--.--.-........````.-``.......--:-::ssssyyyyyyyyss\n");
    printf("ossoossooososhmNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMNNNNNMMMNdyyyyyyyyyysssssssoossooooooosssssssyssyyyhhydmmddddhyyhhhhddhssosssyssyyyyhhhhhhhyyhhyyNMMMMNmhsssssyhdmmmNMmMMMMMMMMMMMNdNMMMMsohNNNmmmhyhhhhhhyyhhhhyyhyyyyyyyyyyyyhhdddddhhhhhhhhdmNmmNNNNNmmmmm+++++++++++////////////:::/+/+++::/+/////-- .---......`.```.........-..----:+ysyhsssssyyssy\n");
    printf("ossssssooososyhdmmmmmmmmmmmmmmmmmNNNNNmmNmmddmdmmmNNMMMNmNMMMMMdyyyyyyyyyssssssssoosoooooooossssssyyyyyyyhyydNmdddhhyhhyhhdmdysssssysyyyyyyhhhhhhyyhyyhMMMMMmdysssyyhdmmmmNMmMMMMMMMMMds+++ymMm+smMMNmmdhhhsyyyyssyyyyhhhhhhyyyyyyyyyyhddddddddhhhhhhhdNNNNNNNNmmms++ooo++++++//////:/:://:::/+++++::/+///::-. .---.........``--...........-:::oyssosssyyyyssh\n");
    printf("osssssssssssssyhhhdddmmmmmddddmmmmdmddhhyyyhhdmmNNMMMMMMNMMMMMMmhyyhhyyysssssssssssooooooooossssssyyyyyyyyyydNddddhhhyyhhhdmdhssssyysyyyyyyhhhhhyyhdyymMMMMNdhyssyyhdmmmmNMMNMMMMMMMho++++++sddhhdmmmmddhhyyyyssssyydmmmdhhhhhhhhhyyyyhhdmdddddmddhhhhhdmNNNNNNNmh+oooo++++++++////:://:/::-+/+/++/::/++///:-``.--..`.......`.:--.....`-..-:///+ooooyyyyhyyyyh\n");
    printf("oysssssssssssssyyyhhddhddddhhhhhhhhhyyyyyydmNNMMMMMNNNMMMMMMMMNmdhhhhyyyyysssssssssooooooooosossssyyyyyyhhhhmNmdddhhhhyhhddmmhysssyysssyyyyyhhhyyyhhyyNMMMNmhyssyyhdmmmmNNMMMMMMMMMMo++++oydmmmmdhhhhhyyyyyyyysssshdmNNNNmhhhhhhhhhdhddddmmdddddmddddhhhdNNNNNNNmoooooo++++++////::::/::::::o/+//+/::/++////.`......`````````.::........----///oooosyyyhhyyssy\n");
    printf("syssssyyyyssssssyyyyhhhhhhhhhhhyhhhhhyyhhmNMMMMMms///sMMMMMMMMNmddhhhhyyyysssssssssoooooooooossssyyyhhddddddhhhdhhddhhyhhdmmmdhyyyyhysssyyyyyhhhyyhhyhNMMMmdhysyhhddmmmNMMMMMMMMMMMMy++oyddddmmmdhyysyyyyyyyssssyhddmmNNNNmmmmmdddddddddddmddddddmddmdddmNNNNNNmsoooo+++//////////:::::::::/o///++/::/++////.`...``` `` `````.--`.....-----://+o++oyyyyysysosh\n");
    printf("sysyyyyyyyysssssssyyyyyyhhhhhhhhhhhhhhhdNMMMMMNs/::::oMMMMMMMMNmmddhhhhyysssssssoooooooooooosssssyhhddyyyhddhyyhhdhddhhhhdmmmddyyyyyysssyyyyyhhyyhdhydMMMNdhyyyyhddmmmNMMMMMMMMMMMMMNhydddhhddmmdhyyssssssyyssydmmmmmmmNNNNNNmmmmmmmmdddddddddddddddddmmmNNNNNmsoooo++/////////:::::::-::::++//////://+++///-`.`````  ` ` ``....`...----:::/+++++ssssssssysosh\n");
    printf("yyyyyyyyyyysssssssssyyyyyyyyhhhhhhhhhhmNMMMMMMy+/::::oMMMMMMMMNmmddhhhhyyssssssooooooooooossssssyhhhhhysyyhhyyyyhhhddhhhhdmmmmdyyyyyhysssyyhyyhhyhdyhNMMNmhhyyyhddmNMMMMMMMMMMMMMMMMNmmdhhhdddmmdhhyyssossssshNMNNmmmmmmmNNNNNmmmmmmmmmmmmddddmmddddmmmmmmNNNmssoo++/////////:::::---:-----++/:..---:+++////:````     `` ```.-.....----://++++++ooosssooyssosh\n");
    printf("yyyyyyyyyyyyssssssssssssyyyyhhhddhhhhdNMMMMMMMMNd+--.oMMMMMMMMNNmddhhhyyysssssoooooooooooossssyyhhhhhyysyyhhyyyyhhhddddhddmmmmdyyyyhhyyysyyyyyhhydhhhMMNmhhhyyhdmNMMMMMMMMMMMMMMMNNmmdhhhhhdddmmddhhysssoossymMMNNmmddddmmNNNmNmmmmmmmmmmmmmmdddmmmmmmmmmmNNmyso++///:/:::::::::----------:++/:-:-.../o+/////.``````  ``````.....-.-:::/++/+++o++oossoooossosy\n");
    printf("sssyyyyyyyyysyyyyssssssssyyyyhhddhhhhmMMMMMMMMMMMm+..oNMMMMMMMNNmddhhyyyysssssooooooooooosssyyyyhhyyyyysyyyhyyyyhhhhhhdddddmmmdhyyyhhhyyyyyyyyyyhdyydMMmdhhhhhhmNMMMMMMMMMMMMMMNmdddhhhhhhhhddddddhhyyssoooshNMMNmmmdddddmNNNNmmNmmmmmmmmmmmmmmmddddddmmmmNdyso++//:::::::::::------------/+///::::--+o+///::.``.`````  ``````..---://+++++++os+ooosoo+osooooy\n");
    printf("sssyyyyyyyyysyyyyyyyyssssssyyyyhhhhhdNMMMMMMMMMMMMm/-oMMMMMMMMNNmddhhyyysssssssosoooososssyyyyyyyyyyyyyyyyyyyyyyhhhhhhdddddmmmdhhyyhdhyyyyysyyyyhhyyNMNdhhhhhhmMMMMMMMMMMNNNMNmddhhyyyyyyhhhhhhddddhyysssoosdMMNNNmmmddddmmNNNNmNmmmmmmmmmmmmmmmmmddddmmmmmyso++//:::::::::::-----------.-++/:///::-:+o+//:::-.```  ``````.....-::/+++++++++osooosso+ooss+oo+s\n");
    printf("yyssyyyyyyyyyyyyyyyyyyssssssyyyyhhhhdNMMMMMMMMMMMMNd/sMMMMMMMMNNmddhhyyysssssssooooooosssyyyyyyyyhyyyyyyyyhhhhyhhhhhhdddddddmmddhyhddhyyyyysyyyyhyyhMMmdddddddNMMMMMNmddhhhhddhhhhyyyysyhdhhyyyhhdddhyyssosyNMMMNNNmmddddddmmmNNNNmmmmmmmmmmmmmmmmmmmddmmdyso+///:::::::::::-------.-....//+/:://::::+oo/::-::-..``  `.-...--:::/++oooooo++oos+ossooooosoo++os\n");
    printf("yyyyyyyyyyyyyyyyyyyyyyyssssssyyyyyhhdmMMMMMMMMMMNNNNhsNMMMMMMMNNmddhhyyyysssssooosssssssyyyhhhyyhhhhhhhhhhdddhhhhdhhhhhhddddddddhyhddhhhysssyyyhhyymMNNNNNMMMMMMMMNdhyyyyyyyyyyyyyyhhyyhdmdhyssyyhdddhysssydMMMMNNNmmdddhhddmmmNNmmmmmmmmmmmmmmmmmmmmmmdhyo+///:::::::::::-:------......://///:/+/:::+so//:-/:-.--...````..---://+oossoo+o+oooosy++ooooooo++oo\n");
    printf("yyyyyyyyyyyyyyyyyyyyyysysssssyyyyhyyhdNMMMMMMMNNNmmNNdNMMMMMMMMNmmdhhyyysysssssssssssyyyhhhddddhdddddddddddddhhhddddhhhhhddhddhhhhdhhhyy:::-syyyyydNMMMMMMMMMMNmdhyyyyyyyyyyyyyyyyyyyyyhdmmdhysssyhhdhyssydMMMMNNNNmmmddddddmmmmmNNmmmmmmmmmmmmmmmmmmdyo+/::::----:-------------.......:////////::::://////://-.----:..-..-:::+/++ooo/+++o+ooosso++oo++oso+++s\n");
    printf("yyyyyyyyyyyyyyyyyyyyyyyyyyysyyyyyhhhhhdNNNNNNmmNmNNNMNNMMMMMMMMNNmdhhyyyysssssssssyyhhhddddmmdddddhhhhhhhhhhhhdhhhhhhhhhhhhhhhyhyhddhhhy://--hyyyhNMMMMMMMMMNdhyssyyyyyyyyyyyyyyhhyyyyyhddmdhyysssyyhhyshmMMMMMNNNNmmmmddddddmddmmNNmmmmmmmmmmmmmmdys+::-----------------------........+//////////::-://////+/:-:--::-----:/:/++ooo++ooososooooo+++o++ooo+o+oy\n");
    printf("hyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhdmmmmmmmmNNMMMMNMMMMMMMMMNmdhhhyyyyyyyyyyyyhhdddmmmdddhhhhhyyhhhhhhhhhhhhhhhhyyhhhyyyhyyyyhdhhhhhs+://hyyydMMMMMMMMNdysssyyyyyhhhyyyyyyyyyyyyyhyyhddmhyssssssyyhdNMMMMMNNNNNNmmmmddddddddmmmmmmmmmmmmmmmdhs+//------------------------.........:///////////:::///:::://:-:::-:-::-:/++/+++oosoossssoo++oo++oooooo++oosy\n");
    printf("hhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhyhhddmmmmmNNNMMMMNmNMMMMMMMMNmddhhyyyyyhhhhyhdddddddddhhhhyyyyyyyyyyyhhhhhhhhyyyyyhhyyyhhhyyhddhhhhyyyssyyyyhNMMMMMMMmyo/:::+syyhhyhhhhyyyyyhhyhhhyyhhddhyyssssyhmNMMMMNNNNNmmmmmmmmmmmddddddmmmmmmmmmmmdys+/::----.......-.....---.............../////////::/:::/:::::///:-:::::::::/+o+ooooosoossssoooo+oooososooo++osyy\n");
    printf("hhhyyyyyhyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhdddddddmNMMMMMddmNMMMMMMMMmmddhhhhhhhhhhhdddddhhhhhhhhhyyyyyyyyyyyhhhhhhyyyyyyyhyyyyhhyyhhdhyyyyhyyyyyyyymMMMMMMNy:..`````.:syyyhhhhhhhhhyhhhhhhhhhhhhyyssydNMMMMNNNNNmmmmmmmmmmmmddddmddddmmmmmmmdhs+/:::--................-.................://///////::/::::/::::://:-::::/:::/++osyso+soossssssssooooossoso+++osysh\n");
    printf("ddhhhhyyyyyyyyyyyhhhhhhhhhhyyyyhhhhhhhhhhhhyyhmMMMMMMMNNMMMMMMMMMNmmmdddddddddddddhhhhhhhyyhyyyyyyyyyyyhhhhhhhyyyyyyyhyyyyhhhyyhddhhhyyhyyyyhyydNMMMNdo:..``````````:syhhhhhhhhhhyhhhdhhhhhhhyyyhmMMMNNNNNmmmmmmmmmmmmmmmmddmmmmmmmmmmdys+//:-------.................................///////:::::/:::::::::://:-::::/:://+syhyooooosssyyyysoosossssss+++ossosh\n");
    printf("dddhhhhyhyyyyyyyyhhhhhhyyhyyyyyyhyyyyyyyyyyyydNMMMMMMMMMMMMMMMMMMNNNNmmmmmddddhhhhhyyyyyyyyyyyyyyyyyyyyhhhhhyyyysyyyhhyyyhhhyyhhdddhhyhyyyyhhyhmMMNh/..``````````````.+yhhhhddddhhhyhhhhdhhyhhdNMMMMNNNNNNNmmmmmmmmNNNNNNNNNNNNNNmmdy+:::--:-----...................................-///////:::::::::::::::://:-::::///:/ohddsss++ssyyyhyssooossyssyo++osoooyh\n");
    printf("dddhhhhhyyyyyyyyyhhhyyyyyhyyyyyyyyyyyyyyyyyhdNMMMMMMMMMMMNNNMMMMMMMNNmmmmdddhhhhhyyyyyyyyyyyyyyyyyyyyyhhhhhhyyyyyyyyhhyyyhhyyyhhdddhyyyyyyhhhhdNms:.```````````````````:yhhddddddhhhhhhhddhdmNMMMMNNNNNNNNNNNNNNNNNNNNNNNNmmmmmdyo/::-------....`-..................................////////:::::::::::::::://:::::::////ydmdhyo+syyyhhyoosoooyssyys+oooo+osyh\n");
    printf("dddddhhhhhhhhyyyyyhyyyyyyhyyyyyyyyyyyyyyyyhmNMMMMMMMMMMMMmddmMMMMMMMNNmmmmddhhhhhyyyyyyyyyyysyyyyyyyyyhhhhhyyyyyyyyhhyyyhhhyyyyhdddyyyyyyhhhhhh+-.``````````````````````:hhddddddhhhhhhhddmmmmmNNNNNNNNNNNNNmmmmmmmmmmmmmmddhs+:---......--.....````....-..........................-////////:::::::::::::::://:::::::////ydmdhssyyssyyso+ooosysyysooosoo+osyyh\n");
    printf("hhdddddhhhhhhhhyyyyyyhyyyyyyyyyyyyyyyyyyyhmMMMNNNNMMMMMMNhsyhNMMMMMMMNNNmmddhhhhyyyyyyyyyyyyyyyyyyyyyhhhhhyyyyyyyyhhhhyyyhyyyyhhddhyyyyyyhhyo/.``````````````````````````/ddmdddddhdhhhddddmmmmmdmmmmmmmmmmddmmmmmmmmmdhso/:-.-.........-.-.....````....-.`........................////////::::::::::::::::://::::://////shmdhyhhyysoooo+oosssssoossoooooysyyh\n");
    printf("yhhhdddddhhhhhhhhhyhhhyyyyyyyyyyyyyyyyyyhmNMNNNNNNNNMMMMmsshdmMMMMMMMMMNNmmmddhhhyyyyyyyyyyyyyyyyyyyyhhhhyyyyyyyyhhhhyyyyyyyyyhhhhyyyyyyhh+-``````````````````````...```..sdmdddddmdddddddddmdmmdddmmmmmmmmmmmmmmmmNdo/.---..-...-........-.....``......-.........................-////////::::::::::::::::://::::://////+sdddyysyosso+ooossyssoshsssoosysosyy\n");
    printf("+sssssyyyyhhhhhhhhyhhhhyyhhhhhyyyhhyyyhhhdmNNmmmNNNNNMNdsydmmmNMMMMMMMMMMNNmmddhhhhhyyyyyyyyyyyyyyyyyhhdhyyyyyyyyhhhyyyyyyyyyyhhhyyyyyhho-`````````````````````.`........-:hmmmdmmmdhmdhddddmmdddddmmmmmmmmmmmmNNMMMy::.................--...`..``..--..--.......................-:////////::::::::::::::::://::::://////++ydmmhysssso+oosyysyssysssooshsooosy\n");
    printf("``       ``.-:/+syyhhhhhhhhhhhyyhhhhyhhhhdmmmmdhhyyyyyyydmNNNmmNMMMMMMMMMMMNNmmddhhhhyyyyyyyyyyyyyyyyhdhhhyyyyyyyhyyyyyyyyyyyhhhyyyyyhs:```````````````````````......-.--::ommmmmmmsossydddmdmmdddddmmmmmmmNNNMMMMMM+-/......-..........--.....``...-....--......................://///////:/:::::::::::::::///////////:/++sdyyhhhhyysoosyyyyyshyssssyyssoooyy\n");
    printf("                 `-/oyhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyhdmNNMNNdddMMMMMMMMMMMMNNmmmdddhhhhhhhyyhhhhhhhhddhhhyyyyyyyyyyyyyyyyyhyhhyyyyyy+.```````````````````.``.......-----:/ohmmmmm+/+o++smddddhhdddddmmdmmNMMMMMMMMN:.:.....-...........-.-.`.`.`........--.....................-/////////:://::::::::::::::/++++//////:/+++hysyyyysssosyhhhyshyyyyysssyooosyy\n");
    printf("                    `./yhhhhhhhhhyhyyyyyyyyyyyyyyyhddmNNMNNmddhdNMMMMMMMMMMMMNNNmmmddddhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyo-...``.```````````````....-.....----::+hydmmmmo+o+:osdyhddhddddmmNNMMMMMMMMMMMMN-`::`....-..`......-...`..`.........-.......................://///////://///::::::::/::////+++++////+oooosydhysooooysddhshhyyyhyhhyssosssy\n");
    printf("                     ``./yhhyhhhhhhhyyyyhyyhhhhhddmmNMMNNNmdhhhhmNMMMMMMMMMMMMMMNNNNmmddhhhhddddddhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyhs:.....````````````````...........----:/+ymmyhhhhhyyyyhhhhhdhmNNMMMMMMMMMMMMMMMMMMN:`.:..`....``.......-..`.```......-.`.....-........`.`.....-/////////::////:::::::::::://:///+oo++//++oossyyyyooossyymhsydyhhhhhhyssooosyy\n");
    printf("```````````           ``.-ohhyhhhhhhhhhhhhhhhdddmNNMMMNNmmdhhhhhhmMMMMMMMMMMMMMMMMMNNmmddddddddddhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyy/.....````````````.`.............-----::/odNNNyhdmdddddddmmNNNMMMMMMMMMMMMMMMMMMMMNNo``-:......`..`........``..`.....-.`..............```......://///////::/::::::::::::::::::::::://+++osooshhysooooosyddhyhhhhhhyyyoooooosyy\n");
    printf("...-...-///:-.`        ``.-+yhhhhhhhddhhhhhhddmNNMMMNNNmddhhhhhhhdmMMMMMMMMMMMMMMMMNNmmdmddddddhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyys-.````.`````..```````..-.........-----::/oyNMMMmydmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmmh```-:```....``..`.............-.``.....................-.-//:://///::::::::::::::::::::::::::::://///oyhyyyoooooosydhyyyyyhhyssoooooossys\n");
    printf("--:/. `:+oososy+.      ```.-+yyyhhhdddhhhddddmNMMMMNNmmddhhhhhhhhhdNMMMMMMMMMMMMMMMNNmmdddddddhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy+..```.```````..................-------::/+smMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmm/```-:``............`.``..`...-.``...............`.....--://///////::::::::::::::::::::::://::::///+ohhyysoooooosyhddhyyhdhyoooooooooyys/\n");
    printf(":yyy.``:+oos::+yh+`      ``.-+yyyhdddddhddmmNNMMMMNNmmmddhhdhhhhhhdmNMMMMMMMMMMMMMMNNmmddddhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyys:.`......`````..................------:://+smMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmdddh.` `--....`-.....`.`.......-.-..`...............``....--//:///////::/::/::::::::::/:::::::///://++++osyyssooosssyhhhyydhhyooooooo+ooooo:\n");
    printf(".sss``.:+oos-..-+ss:     ```.:oyyyyhddddmmNNNMMMMNNNmmmdddddddhhhhhddmNNMMMMMMMMMMMMNNmmdddhhhyyyyyyyyyyyyyyyyyyyyyyyyyys+:.........`````.............-...-------:/++shmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmdddddds.```-:-..---....`..........-.`..............`.``.....-//////////:::/:::::::/o+++////:://///+ossyssoosssssssssssyyyyhhhhysosoooooossyy/.\n");

    return 0;
}



























